--- 
javascripts: 
- base:
  - prototype
  - effects
  - controls
  - active_scaffold/default/rico_corner
  - active_scaffold/default/dhtml_history
  - active_scaffold/default/form_enhancements
  - active_scaffold/default/active_scaffold
  - application
  - help
stylesheets: 
- base: 
  - reset
  - application
  - help
  - tooltips
  - auto_complete
  - active_scaffold/default/stylesheet
  - active_scaffold_overrides
- ie:
  - active_scaffold/default/stylesheet-ie
  - ie_fixes
