--- 
javascripts: 
- base: 
  - prototype
  - effects
  - controls
  - application
  - prototabs/prototabs
  - active_scaffold/default/active_scaffold
stylesheets: 
- base: 
  - reset
  - application
  - active_scaffold/default/stylesheet
  - active_scaffold_overrides
- ie:
  - active_scaffold/default/stylesheet-ie
