CREATE TABLE `auxLakesWithDepths` (
  `WaterBodyID` double(15,5) DEFAULT NULL,
  `WaterBodyName` varchar(40) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `WaterBodyTypeCd` varchar(4) DEFAULT NULL,
  `StartRouteMeas` double(15,5) DEFAULT NULL,
  `EndRouteMeas` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `auxLakesWithSurveys` (
  `WaterBodyID` double(15,5) DEFAULT NULL,
  `WaterBodyName` varchar(40) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `WaterBodyTypeCd` varchar(4) DEFAULT NULL,
  `StartRouteMeas` double(15,5) DEFAULT NULL,
  `EndRouteMeas` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `auxStockedWaters` (
  `WaterBodyID` double(15,5) DEFAULT NULL,
  `WaterBodyName` varchar(50) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `WaterBodyTypeCd` varchar(4) DEFAULT NULL,
  `StartRouteMeas` double(15,5) DEFAULT NULL,
  `EndRouteMeas` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `WATERID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `auxStreamsWithSurveys` (
  `RIVER_SYS` smallint(5) DEFAULT NULL,
  `WaterBodyID` double(15,5) DEFAULT NULL,
  `WaterBodyName` varchar(40) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `STARTPOINT` varchar(50) DEFAULT NULL,
  `ENDPOINT` varchar(50) DEFAULT NULL,
  `StreamLength_km` double(15,5) DEFAULT NULL,
  `StartRouteMeas` double(15,5) DEFAULT NULL,
  `EndRouteMeas` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `auxUSERDBNonRestrictedActivityIDs` (
  `AgencyCd` varchar(4) DEFAULT NULL,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `AquaticActivityCd` smallint(5) DEFAULT NULL,
  `AquaticActivity` varchar(50) DEFAULT NULL,
  `AquaticActivityStartDate` varchar(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `auxUserDBElectrofishingFopEstimate` (
  `EFPopulationEstimateID` int(10) NOT NULL AUTO_INCREMENT,
  `oldEFPopulationEstimateID` int(10) DEFAULT NULL,
  `EFDataID` int(10) DEFAULT NULL,
  `TempDataID` int(10) DEFAULT NULL,
  `oldEFDataID` double(15,5) DEFAULT NULL,
  `EFMRDataID` int(10) DEFAULT NULL,
  `EFDataInd` tinyint(1) NOT NULL DEFAULT '0',
  `AquaticActivityID` int(10) DEFAULT NULL,
  `OLDAquaticActivityID` double(15,5) DEFAULT NULL,
  `Formula` varchar(26) DEFAULT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `FishAgeClass` varchar(10) DEFAULT NULL,
  `RelativeSizeClass` varchar(10) DEFAULT NULL,
  `AveForkLength_cm` double(15,5) DEFAULT NULL,
  `AveWeight_gm` double(15,5) DEFAULT NULL,
  `PopulationParameter` varchar(20) DEFAULT NULL,
  `PopulationEstimate` double(15,5) DEFAULT NULL,
  `AutoCalculatedInd` tinyint(1) NOT NULL DEFAULT '0',
  `Comments` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`EFPopulationEstimateID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `EFASSMT_ID` (`OLDAquaticActivityID`),
  KEY `EFDATA_ID` (`oldEFDataID`),
  KEY `EFDataID` (`EFDataID`),
  KEY `EFPopulationEstimateID` (`oldEFPopulationEstimateID`),
  KEY `EFPopulationEstimateID1` (`EFPopulationEstimateID`),
  KEY `TempEFDataID` (`TempDataID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `auxUserDBSelectedActivities` (
  `AquaticActivityID` int(10) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `auxUserDBSelectedSiteUse` (
  `AquaticSiteUseID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticSiteID` int(10) DEFAULT NULL,
  `AquaticActivityCd` smallint(5) DEFAULT NULL,
  `AgencyCd` varchar(4) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticSiteUseID`)
) ENGINE=InnoDB AUTO_INCREMENT=6782 DEFAULT CHARSET=utf8;

CREATE TABLE `auxUserDBSelectedSites` (
  `AquaticSiteUseID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticSiteID` int(10) DEFAULT NULL,
  `AquaticActivityCd` smallint(5) DEFAULT NULL,
  `AgencyCd` varchar(4) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticSiteUseID`)
) ENGINE=InnoDB AUTO_INCREMENT=6171 DEFAULT CHARSET=utf8;

CREATE TABLE `cdAgency` (
  `AgencyCd` varchar(5) NOT NULL,
  `Agency` varchar(60) DEFAULT NULL,
  `AgencyType` varchar(4) DEFAULT NULL,
  `DataRulesInd` varchar(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`AgencyCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdAquaticActivity` (
  `AquaticActivityCd` smallint(5) NOT NULL AUTO_INCREMENT,
  `AquaticActivity` varchar(50) DEFAULT NULL,
  `AquaticActivityCategory` varchar(30) DEFAULT NULL,
  `Duration` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityCd`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;

CREATE TABLE `cdAquaticActivityMethod` (
  `AquaticMethodCd` smallint(5) NOT NULL AUTO_INCREMENT,
  `AquaticActivityCd` smallint(5) DEFAULT NULL,
  `AquaticMethod` varchar(30) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticMethodCd`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8;

CREATE TABLE `cdCountyParish` (
  `CountyParishID` int(10) NOT NULL AUTO_INCREMENT,
  `OldCountyCd` varchar(10) DEFAULT NULL,
  `NewCountyCd` varchar(11) DEFAULT NULL,
  `County` varchar(17) DEFAULT NULL,
  `OldParishCd` varchar(10) DEFAULT NULL,
  `NewParishCd` varchar(12) DEFAULT NULL,
  `Parish` varchar(22) DEFAULT NULL,
  `OldCountyParishCd` varchar(6) DEFAULT NULL,
  `NewCountyParishCd` varchar(7) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`CountyParishID`),
  KEY `CountyParishID` (`CountyParishID`),
  KEY `NewCountyCd` (`NewCountyCd`),
  KEY `NewParishCd` (`NewParishCd`)
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=utf8;

CREATE TABLE `cdEnvironmentalObservations` (
  `ObservationID` int(10) NOT NULL AUTO_INCREMENT,
  `ObservationCategory` varchar(40) DEFAULT NULL,
  `ObservationGroup` varchar(50) DEFAULT NULL,
  `Observation` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`ObservationID`),
  KEY `ObservationID` (`ObservationID`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishAgeClass` (
  `FishAgeClass` varchar(25) NOT NULL,
  `FishAgeClassCategory` varchar(20) DEFAULT NULL,
  `StockingInd` tinyint(1) NOT NULL DEFAULT '0',
  `ElectrofishInd` tinyint(1) NOT NULL DEFAULT '0',
  `FishCountInd` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishAgeClass`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishMark` (
  `FishMarkCd` int(10) NOT NULL,
  `FishMark` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishMarkCd`),
  KEY `Fin Status Code` (`FishMarkCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishMortalityCause` (
  `MortalityCauseCd` int(10) NOT NULL,
  `CauseOfMortality` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`MortalityCauseCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishParasiteClass` (
  `ParasiteClassCd` varchar(4) NOT NULL,
  `ParasiteClass` varchar(20) DEFAULT NULL,
  `Location` varchar(24) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`ParasiteClassCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishPopulationFormula` (
  `FormulaCd` int(10) NOT NULL AUTO_INCREMENT,
  `Formula` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FormulaCd`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishPopulationParameter` (
  `PopulationParameter` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishSpecies` (
  `FishSpeciesCd` varchar(2) NOT NULL,
  `FishSpecies` varchar(30) DEFAULT NULL,
  `StockedInd` tinyint(1) NOT NULL DEFAULT '0',
  `ElectrofishInd` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishSpeciesCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishStatus` (
  `FishStatusCd` varchar(10) NOT NULL,
  `FishStatus` varchar(50) DEFAULT NULL,
  `FishStatusType` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishStatusCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdFishStomachContent` (
  `StomachContentCd` int(10) NOT NULL AUTO_INCREMENT,
  `StomachContent` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`StomachContentCd`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

CREATE TABLE `cdHabitatUnitComment` (
  `CommentCd` varchar(2) NOT NULL,
  `Comment` varchar(30) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`CommentCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdInstrument` (
  `InstrumentCd` int(10) NOT NULL AUTO_INCREMENT,
  `Instrument` varchar(50) DEFAULT NULL,
  `Instrument_Category` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`InstrumentCd`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

CREATE TABLE `cdMeasureInstrument` (
  `MeasureInstrumentCd` int(10) NOT NULL AUTO_INCREMENT,
  `OandMCd` int(10) DEFAULT NULL,
  `InstrumentCd` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`MeasureInstrumentCd`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8;

CREATE TABLE `cdMeasureUnit` (
  `MeasureUnitCd` int(10) NOT NULL AUTO_INCREMENT,
  `OandMCd` int(10) DEFAULT NULL,
  `UnitofMeasureCd` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`MeasureUnitCd`),
  KEY `cdMeasureUnitOandMCd` (`OandMCd`),
  KEY `cdMeasureUnitUnitofMeasureCd` (`UnitofMeasureCd`)
) ENGINE=InnoDB AUTO_INCREMENT=183 DEFAULT CHARSET=utf8;

CREATE TABLE `cdOandM` (
  `OandMCd` int(10) NOT NULL AUTO_INCREMENT,
  `OandM_Type` varchar(16) DEFAULT NULL,
  `OandM_Category` varchar(40) DEFAULT NULL,
  `OandM_Group` varchar(50) DEFAULT NULL,
  `OandM_Parameter` varchar(50) DEFAULT NULL,
  `OandM_ParameterCd` varchar(30) DEFAULT NULL,
  `OandM_ValuesInd` tinyint(1) NOT NULL DEFAULT '0',
  `OandM_DetailsInd` tinyint(1) NOT NULL DEFAULT '0',
  `FishPassageInd` tinyint(1) NOT NULL DEFAULT '0',
  `BankInd` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`OandMCd`),
  KEY `ObservationID` (`OandMCd`)
) ENGINE=InnoDB AUTO_INCREMENT=229 DEFAULT CHARSET=utf8;

CREATE TABLE `cdOandMValues` (
  `OandMValuesCd` int(10) NOT NULL AUTO_INCREMENT,
  `OandMCd` int(10) DEFAULT NULL,
  `Value` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`OandMValuesCd`),
  KEY `O&M_ID` (`OandMCd`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

CREATE TABLE `cdSampleCollectionMethod` (
  `SampleMethodCd` int(10) NOT NULL AUTO_INCREMENT,
  `SampleMethod` varchar(30) DEFAULT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SampleMethodCd`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

CREATE TABLE `cdSampleGear` (
  `SampleGearCd` int(10) NOT NULL AUTO_INCREMENT,
  `SampleGear` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SampleGearCd`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

CREATE TABLE `cdSex` (
  `SexCd` varchar(1) NOT NULL,
  `Sex` varchar(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SexCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdStreamChannelType` (
  `ChannelCd` varchar(1) NOT NULL,
  `ChannelType` varchar(6) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`ChannelCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdStreamEmbeddedness` (
  `EmbeddedCd` varchar(1) NOT NULL,
  `Embeddedness` varchar(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`EmbeddedCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdStreamType` (
  `StreamTypeCd` varchar(2) NOT NULL,
  `StreamType` varchar(24) DEFAULT NULL,
  `StreamTypeGroup` varchar(6) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`StreamTypeCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdUnitofMeasure` (
  `UnitofMeasureCd` int(10) NOT NULL AUTO_INCREMENT,
  `UnitofMeasure` varchar(50) DEFAULT NULL,
  `UnitofMeasureAbv` varchar(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`UnitofMeasureCd`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;

CREATE TABLE `cdWaterChemistryQualifier` (
  `QualifierCd` varchar(4) NOT NULL,
  `Qualifier` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`QualifierCd`),
  KEY `cdWaterChemistryQualifierQualif` (`QualifierCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdWaterParameter` (
  `WaterParameterCd` int(10) NOT NULL,
  `WaterParameter` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterParameterCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdWaterSource` (
  `WaterSourceCd` varchar(4) NOT NULL,
  `WaterSource` varchar(20) DEFAULT NULL,
  `WaterSourceType` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterSourceCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cdWaterSourceType` (
  `WaterSourceType` varchar(30) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterSourceType`),
  KEY `cdWaterSourceTypeWaterSourceType` (`WaterSourceType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `coordinate_sources` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `coordinate_sources_coordinate_systems` (
  `coordinate_source_id` int(11) DEFAULT NULL,
  `coordinate_system_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `coordinate_systems` (
  `epsg` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `display_name` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`epsg`)
) ENGINE=InnoDB AUTO_INCREMENT=26921 DEFAULT CHARSET=utf8;

CREATE TABLE `gmap_locations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `locatable_id` int(11) DEFAULT NULL,
  `locatable_type` varchar(255) DEFAULT NULL,
  `latitude` decimal(15,10) DEFAULT NULL,
  `longitude` decimal(15,10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `locatable_index` (`locatable_id`,`locatable_type`)
) ENGINE=InnoDB AUTO_INCREMENT=1293 DEFAULT CHARSET=utf8;

CREATE TABLE `rpttblBasinOrderingScheme` (
  `Level1No` varchar(2) NOT NULL,
  `Level1Name` varchar(40) DEFAULT NULL,
  `OceanName` varchar(20) DEFAULT NULL,
  `Level1Area_km2` double(15,5) DEFAULT NULL,
  `Level1Area_Percent` double(15,5) DEFAULT NULL,
  `Order` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`Level1No`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `schema_migrations` (
  `version` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  UNIQUE KEY `unique_schema_migrations` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblAnglingLease` (
  `RegulatedWaterID` int(10) NOT NULL,
  `LeaseNo` smallint(5) DEFAULT NULL,
  `LeaseDesc` varchar(254) DEFAULT NULL,
  `StreamLength_km` double(15,5) DEFAULT NULL,
  `NoRodsPerDay` smallint(5) DEFAULT NULL,
  `NoRodsPerYear` varchar(24) DEFAULT NULL,
  `ExpiryYear` varchar(4) DEFAULT NULL,
  `LodgeName` varchar(20) DEFAULT NULL,
  `Lessee` varchar(45) DEFAULT NULL,
  `LesseeAddress1` varchar(30) DEFAULT NULL,
  `LesseeAddress2` varchar(20) DEFAULT NULL,
  `LesseeCity` varchar(20) DEFAULT NULL,
  `LesseProv` varchar(2) DEFAULT NULL,
  `LesseePostalCd` varchar(7) DEFAULT NULL,
  `Contact1` varchar(20) DEFAULT NULL,
  `Contact1Title` varchar(20) DEFAULT NULL,
  `Contact1Dept` varchar(25) DEFAULT NULL,
  `Contact1Phone` varchar(14) DEFAULT NULL,
  `Contact1Fax` varchar(14) DEFAULT NULL,
  `Contact2` varchar(24) DEFAULT NULL,
  `Contact2Title` varchar(20) DEFAULT NULL,
  `Contact2Dept` varchar(20) DEFAULT NULL,
  `Contact2Phone` varchar(14) DEFAULT NULL,
  `Contact2Fax` varchar(14) DEFAULT NULL,
  `Manager` varchar(21) DEFAULT NULL,
  `ManagerPhone` varchar(14) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`RegulatedWaterID`),
  KEY `{D3655704-EBA1-41D7-8CCB-412119` (`RegulatedWaterID`),
  KEY `LEASE_ID` (`LeaseNo`),
  KEY `RegulatedWatersID` (`RegulatedWaterID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblAnglingLicenseSales` (
  `LicenseSalesID` int(10) NOT NULL AUTO_INCREMENT,
  `LicenseCd` int(10) DEFAULT NULL,
  `Residence` varchar(255) DEFAULT NULL,
  `LicenseType` varchar(255) DEFAULT NULL,
  `LicenseClass` varchar(255) DEFAULT NULL,
  `LicenseDesc` varchar(255) DEFAULT NULL,
  `Year` int(10) DEFAULT NULL,
  `NoSold` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`LicenseSalesID`)
) ENGINE=InnoDB AUTO_INCREMENT=1401 DEFAULT CHARSET=utf8;

CREATE TABLE `tblAquaticActivity` (
  `AquaticActivityID` int(10) NOT NULL AUTO_INCREMENT,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `Project` varchar(100) DEFAULT NULL,
  `PermitNo` varchar(20) DEFAULT NULL,
  `AquaticProgramID` int(10) DEFAULT NULL,
  `AquaticActivityCd` smallint(5) DEFAULT NULL,
  `AquaticMethodCd` smallint(5) DEFAULT NULL,
  `oldAquaticSiteID` int(10) DEFAULT NULL,
  `AquaticSiteID` int(10) DEFAULT NULL,
  `AquaticActivityStartDate` varchar(10) DEFAULT NULL,
  `AquaticActivityEndDate` varchar(10) DEFAULT NULL,
  `AquaticActivityStartTime` varchar(6) DEFAULT NULL,
  `AquaticActivityEndTime` varchar(6) DEFAULT NULL,
  `Year` varchar(4) DEFAULT NULL,
  `AgencyCd` varchar(4) DEFAULT NULL,
  `Agency2Cd` varchar(4) DEFAULT NULL,
  `Agency2Contact` varchar(50) DEFAULT NULL,
  `AquaticActivityLeader` varchar(50) DEFAULT NULL,
  `Crew` varchar(50) DEFAULT NULL,
  `WeatherConditions` varchar(50) DEFAULT NULL,
  `WaterTemp_C` double(7,2) DEFAULT NULL,
  `AirTemp_C` double(7,2) DEFAULT NULL,
  `WaterLevel` varchar(6) DEFAULT NULL,
  `WaterLevel_cm` varchar(50) DEFAULT NULL,
  `WaterLevel_AM_cm` varchar(50) DEFAULT NULL,
  `WaterLevel_PM_cm` varchar(50) DEFAULT NULL,
  `Siltation` varchar(50) DEFAULT NULL,
  `PrimaryActivityInd` tinyint(1) NOT NULL DEFAULT '0',
  `Comments` varchar(250) DEFAULT NULL,
  `DateEntered` datetime DEFAULT NULL,
  `IncorporatedInd` tinyint(1) NOT NULL DEFAULT '0',
  `DateTransferred` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityID`),
  KEY `{33D6B2E4-F11A-47D1-BFE4-EE52E8` (`AquaticSiteID`),
  KEY `{66945D2F-F4E9-46B3-B601-8B4AC0` (`AquaticActivityCd`),
  KEY `{86A93E88-27E1-4293-8F8F-51509C` (`AquaticProgramID`),
  KEY `{D79D562C-FC0D-4C7B-AF79-95EFDA` (`Agency2Cd`),
  KEY `{DBF31B0D-A36E-42EC-A246-E33178` (`AgencyCd`),
  KEY `{FFCC8125-2385-49D8-9E05-364C40` (`Agency2Cd`),
  KEY `AquaticActivityID1` (`AquaticActivityID`),
  KEY `AquaticProgramID` (`AquaticProgramID`),
  KEY `FisheriesSiteID` (`AquaticSiteID`),
  KEY `OldAquaticActivityID` (`TempAquaticActivityID`),
  KEY `oldAquaticSiteID` (`oldAquaticSiteID`)
) ENGINE=InnoDB AUTO_INCREMENT=150639 DEFAULT CHARSET=utf8;

CREATE TABLE `tblAquaticProgram` (
  `AquaticProgramID` int(10) NOT NULL,
  `AquaticProgramName` varchar(30) DEFAULT NULL,
  `AquaticProgramPurpose` varchar(150) DEFAULT NULL,
  `AquaticProgramStartDate` datetime DEFAULT NULL,
  `AquaticProgramEndDate` datetime DEFAULT NULL,
  `AgencyCd` varchar(4) DEFAULT NULL,
  `AquaticProgramLeader` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticProgramID`),
  KEY `{D2FEB2BB-F414-4F7D-8613-ACB906` (`AgencyCd`),
  KEY `AquaticProgramID` (`AquaticProgramID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblAquaticSite` (
  `AquaticSiteID` int(10) NOT NULL AUTO_INCREMENT,
  `oldAquaticSiteID` int(10) DEFAULT NULL,
  `RiverSystemID` smallint(5) DEFAULT NULL,
  `WaterBodyID` int(10) DEFAULT NULL,
  `WaterBodyName` varchar(50) DEFAULT NULL,
  `AquaticSiteName` varchar(100) DEFAULT NULL,
  `AquaticSiteDesc` varchar(250) DEFAULT NULL,
  `HabitatDesc` varchar(50) DEFAULT NULL,
  `ReachNo` int(10) DEFAULT NULL,
  `StartDesc` varchar(100) DEFAULT NULL,
  `EndDesc` varchar(100) DEFAULT NULL,
  `StartRouteMeas` double(15,5) DEFAULT NULL,
  `EndRouteMeas` double(15,5) DEFAULT NULL,
  `SiteType` varchar(20) DEFAULT NULL,
  `SpecificSiteInd` varchar(1) DEFAULT NULL,
  `GeoReferencedInd` varchar(1) DEFAULT NULL,
  `DateEntered` datetime DEFAULT NULL,
  `IncorporatedInd` tinyint(1) NOT NULL DEFAULT '0',
  `CoordinateSource` varchar(50) DEFAULT NULL,
  `CoordinateSystem` varchar(50) DEFAULT NULL,
  `XCoordinate` varchar(50) DEFAULT NULL,
  `YCoordinate` varchar(50) DEFAULT NULL,
  `CoordinateUnits` varchar(50) DEFAULT NULL,
  `Comments` varchar(150) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticSiteID`),
  KEY `{047A49A9-3B29-47B9-B429-4EBFC4` (`WaterBodyID`),
  KEY `{A85D1309-1E35-4A86-8D76-67637B` (`RiverSystemID`),
  KEY `AssmtSiteID` (`AquaticSiteID`),
  KEY `oldAquaticSiteID` (`oldAquaticSiteID`),
  KEY `RiverSystemID` (`RiverSystemID`),
  KEY `WaterBodyID` (`WaterBodyID`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;

CREATE TABLE `tblAquaticSiteAgencyUse` (
  `AquaticSiteUseID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticSiteID` int(10) DEFAULT NULL,
  `AquaticActivityCd` smallint(5) DEFAULT NULL,
  `AquaticSiteType` varchar(30) DEFAULT NULL,
  `AgencyCd` varchar(4) DEFAULT NULL,
  `AgencySiteID` varchar(16) DEFAULT NULL,
  `StartYear` varchar(4) DEFAULT NULL,
  `EndYear` varchar(4) DEFAULT NULL,
  `YearsActive` varchar(20) DEFAULT NULL,
  `DateEntered` datetime DEFAULT NULL,
  `IncorporatedInd` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticSiteUseID`),
  KEY `{AE11D8D8-9E33-4740-BC97-E80094` (`AquaticSiteID`),
  KEY `AgencySiteID` (`AgencySiteID`),
  KEY `AssmtSiteID` (`AquaticSiteUseID`),
  KEY `WaterBodyID` (`AquaticSiteID`)
) ENGINE=InnoDB AUTO_INCREMENT=7004 DEFAULT CHARSET=utf8;

CREATE TABLE `tblBacterialAnalysis` (
  `BacterialAnalysisID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `DOE_LabNo` varchar(8) DEFAULT NULL,
  `DOE_FieldNo` varchar(10) DEFAULT NULL,
  `SampleDepth_m` double(15,5) DEFAULT NULL,
  `WaterTemp_C` double(15,5) DEFAULT NULL,
  `QualifierA` varchar(2) DEFAULT NULL,
  `FaecalColiformCount_A` double(15,5) DEFAULT NULL,
  `QualifierB` varchar(2) DEFAULT NULL,
  `FaecalColiformCount_B` double(15,5) DEFAULT NULL,
  `L_TotalColiforms` varchar(1) DEFAULT NULL,
  `TotalColiforms` int(10) DEFAULT NULL,
  `Ecoli` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`BacterialAnalysisID`),
  KEY `{B0CA8FCD-3C0D-4472-B2A9-904822` (`AquaticActivityID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `BacterialAnalysisID` (`BacterialAnalysisID`),
  KEY `OldAquaticActivityID` (`TempAquaticActivityID`)
) ENGINE=InnoDB AUTO_INCREMENT=602 DEFAULT CHARSET=utf8;

CREATE TABLE `tblBroodstockCollection` (
  `AquaticActivityID` int(10) NOT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `Wild_M_MSW` double(15,5) DEFAULT NULL,
  `Wild_F_MSW` double(15,5) DEFAULT NULL,
  `Clipped_M_MSW` double(15,5) DEFAULT NULL,
  `Clipped_F_MSW` double(15,5) DEFAULT NULL,
  `Total_M_MSW` double(15,5) DEFAULT NULL,
  `Total_F_MSW` double(15,5) DEFAULT NULL,
  `Total_MSW` double(15,5) DEFAULT NULL,
  `Wild_M_Grilse` double(15,5) DEFAULT NULL,
  `Wild_F_Grilse` double(15,5) DEFAULT NULL,
  `Clipped_M_Grilse` double(15,5) DEFAULT NULL,
  `Clipped_F_Grilse` double(15,5) DEFAULT NULL,
  `Total_M_Grilse` double(15,5) DEFAULT NULL,
  `Total_F_Grilse` double(15,5) DEFAULT NULL,
  `Total_Grilse` double(15,5) DEFAULT NULL,
  `Total_F_ASalmon` double(15,5) DEFAULT NULL,
  `Total_M_ASalmon` double(15,5) DEFAULT NULL,
  `Total_ASalmon` double(15,5) DEFAULT NULL,
  `Comments` varchar(250) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityID`),
  KEY `{980D252C-07FE-480B-9235-EA23BD` (`AquaticActivityID`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblCrownReserve` (
  `RegulatedWaterID` int(10) NOT NULL,
  `AnglingFishSpecies` varchar(20) DEFAULT NULL,
  `StreamLength_km` double(15,5) DEFAULT NULL,
  `NoPools` smallint(5) DEFAULT NULL,
  `NoDays` smallint(5) DEFAULT NULL,
  `MaxRodPerDay` smallint(5) DEFAULT NULL,
  `AccommodationsInd` varchar(1) DEFAULT NULL,
  `StartYear` varchar(10) DEFAULT NULL,
  `EndYear` varchar(10) DEFAULT NULL,
  `ActiveInd` varchar(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`RegulatedWaterID`),
  KEY `{2F73944A-EE45-4C58-B41D-F6542A` (`RegulatedWaterID`),
  KEY `RegulatedWatersID` (`RegulatedWaterID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblDraingeUnit` (
  `DrainageCd` varchar(17) NOT NULL,
  `Level1No` varchar(2) DEFAULT NULL,
  `Level1Name` varchar(40) DEFAULT NULL,
  `Level2No` varchar(2) DEFAULT NULL,
  `Level2Name` varchar(50) DEFAULT NULL,
  `Level3No` varchar(2) DEFAULT NULL,
  `Level3Name` varchar(50) DEFAULT NULL,
  `Level4No` varchar(2) DEFAULT NULL,
  `Level4Name` varchar(50) DEFAULT NULL,
  `Level5No` varchar(2) DEFAULT NULL,
  `Level5Name` varchar(50) DEFAULT NULL,
  `Level6No` varchar(2) DEFAULT NULL,
  `Level6Name` varchar(50) DEFAULT NULL,
  `UnitName` varchar(55) DEFAULT NULL,
  `UnitType` varchar(4) DEFAULT NULL,
  `BorderInd` varchar(1) DEFAULT NULL,
  `StreamOrder` smallint(5) DEFAULT NULL,
  `Area_ha` double(15,5) DEFAULT NULL,
  `Area_percent` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`DrainageCd`),
  KEY `{C26A40DF-1604-4BE7-BDBD-F8BC6C` (`Level1No`),
  KEY `tblDraingeUnitsDrainageCd` (`DrainageCd`),
  KEY `tblDraingeUnitsLevel1No` (`Level1No`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblElectrofishingData` (
  `EFDataID` int(10) NOT NULL AUTO_INCREMENT,
  `oldEFDataID` double(15,5) DEFAULT NULL,
  `TempDataID` int(10) DEFAULT NULL,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` double(15,5) DEFAULT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `FishAgeClass` varchar(10) DEFAULT NULL,
  `RelativeSizeClass` varchar(10) DEFAULT NULL,
  `AveWeight_gm` double(15,5) DEFAULT NULL,
  `AveForkLength_cm` double(15,5) DEFAULT NULL,
  `AveTotalLength_cm` double(15,5) DEFAULT NULL,
  `Sweep1NoFish` double(15,5) DEFAULT NULL,
  `Sweep1Time_s` double(15,5) DEFAULT NULL,
  `Sweep2NoFish` double(15,5) DEFAULT NULL,
  `Sweep2Time_s` double(15,5) DEFAULT NULL,
  `Sweep3NoFish` double(15,5) DEFAULT NULL,
  `Sweep3Time_s` double(15,5) DEFAULT NULL,
  `Sweep4NoFish` double(15,5) DEFAULT NULL,
  `Sweep4Time_s` double(15,5) DEFAULT NULL,
  `Sweep5NoFish` double(15,5) DEFAULT NULL,
  `Sweep5Time_s` double(15,5) DEFAULT NULL,
  `Sweep6NoFish` double(15,5) DEFAULT NULL,
  `Sweep6Time_s` double(15,5) DEFAULT NULL,
  `TotalNoSweeps` int(10) DEFAULT NULL,
  `TotalNoFish` double(15,5) DEFAULT NULL,
  `PercentClipped` double(15,5) DEFAULT NULL,
  `Comments` varchar(100) DEFAULT NULL,
  `DW_Comments` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`EFDataID`),
  KEY `{196E57D0-3F38-43B2-B4E7-3A9546` (`AquaticActivityID`),
  KEY `{3307D7AA-47A2-4D30-B30E-4596D1` (`FishSpeciesCd`),
  KEY `{D2C885E2-CCEF-47E5-AF27-170490` (`FishAgeClass`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `EFASSMT_ID` (`TempAquaticActivityID`),
  KEY `EFDATA_ID` (`oldEFDataID`),
  KEY `EFDataID` (`EFDataID`),
  KEY `TempEFDataID` (`TempDataID`)
) ENGINE=InnoDB AUTO_INCREMENT=39414 DEFAULT CHARSET=utf8;

CREATE TABLE `tblElectrofishingMarkRecaptureData` (
  `EFMRDataID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` double(15,5) DEFAULT NULL,
  `TempDataID` int(10) DEFAULT NULL,
  `RecaptureTime` smallint(5) DEFAULT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `FishAgeClass` varchar(10) DEFAULT NULL,
  `AveWeight_gm` double(15,5) DEFAULT NULL,
  `AveForkLength_cm` double(15,5) DEFAULT NULL,
  `AveTotalLength_cm` double(15,5) DEFAULT NULL,
  `MarkCount` double(15,5) DEFAULT NULL,
  `MarkMarked` double(15,5) DEFAULT NULL,
  `MarkMorts` double(15,5) DEFAULT NULL,
  `RecaptureCount` double(15,5) DEFAULT NULL,
  `RecaptureUnmarked` double(15,5) DEFAULT NULL,
  `RecaptureMarked` double(15,5) DEFAULT NULL,
  `RecaptureMorts` double(15,5) DEFAULT NULL,
  `MarkEfficiency` double(15,5) DEFAULT NULL,
  `Comments` varchar(100) DEFAULT NULL,
  `DW_Comments` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`EFMRDataID`),
  KEY `{22F2CEBB-F47B-4837-8840-C009FB` (`FishAgeClass`),
  KEY `{B2C296E5-A98F-454E-A7A0-2A3DFE` (`AquaticActivityID`),
  KEY `{E1056899-F963-4116-855D-6F47EE` (`FishSpeciesCd`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `EFASSMT_ID` (`TempAquaticActivityID`),
  KEY `EFDATA_ID` (`EFMRDataID`),
  KEY `TempDataID` (`TempDataID`)
) ENGINE=InnoDB AUTO_INCREMENT=961 DEFAULT CHARSET=utf8;

CREATE TABLE `tblElectrofishingMethodDetail` (
  `AquaticActivityDetailID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `Device` varchar(20) DEFAULT NULL,
  `SiteSetup` varchar(6) DEFAULT NULL,
  `NoSweeps` smallint(5) DEFAULT NULL,
  `StreamLength_m` double(7,2) DEFAULT NULL,
  `Area_m2` double(7,2) DEFAULT NULL,
  `Voltage` double(15,5) DEFAULT NULL,
  `Frequency_Hz` double(15,5) DEFAULT NULL,
  `DutyCycle` double(15,5) DEFAULT NULL,
  `POWSetting` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityDetailID`),
  KEY `{974003F4-D516-4FAA-9C71-2FC24E` (`AquaticActivityID`),
  KEY `AquaticActivityDetailsID` (`AquaticActivityDetailID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `AssmtPrgrmID` (`TempAquaticActivityID`)
) ENGINE=InnoDB AUTO_INCREMENT=4126 DEFAULT CHARSET=utf8;

CREATE TABLE `tblElectrofishingPopulationEstimate` (
  `EFPopulationEstimateID` int(10) NOT NULL AUTO_INCREMENT,
  `oldEFPopulationEstimateID` int(10) DEFAULT NULL,
  `EFDataID` int(10) DEFAULT NULL,
  `TempDataID` int(10) DEFAULT NULL,
  `oldEFDataID` double(15,5) DEFAULT NULL,
  `EFMRDataID` int(10) DEFAULT NULL,
  `EFDataInd` tinyint(1) NOT NULL DEFAULT '0',
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` double(15,5) DEFAULT NULL,
  `Formula` varchar(26) DEFAULT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `FishAgeClass` varchar(10) DEFAULT NULL,
  `RelativeSizeClass` varchar(10) DEFAULT NULL,
  `AveForkLength_cm` double(15,5) DEFAULT NULL,
  `AveWeight_gm` double(15,5) DEFAULT NULL,
  `PopulationParameter` varchar(20) DEFAULT NULL,
  `PopulationEstimate` double(15,5) DEFAULT NULL,
  `AutoCalculatedInd` tinyint(1) NOT NULL DEFAULT '0',
  `Comments` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`EFPopulationEstimateID`),
  KEY `{3054E6F5-67BE-4433-BA0D-203C0F` (`FishAgeClass`),
  KEY `{619029C0-02D2-4149-BE10-808545` (`AquaticActivityID`),
  KEY `{D6A691C5-AB3C-4A65-9711-F88235` (`FishSpeciesCd`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `EFASSMT_ID` (`TempAquaticActivityID`),
  KEY `EFDATA_ID` (`oldEFDataID`),
  KEY `EFDataID` (`EFDataID`),
  KEY `EFPopulationEstimateID` (`oldEFPopulationEstimateID`),
  KEY `EFPopulationEstimateID1` (`EFPopulationEstimateID`),
  KEY `TempEFDataID` (`TempDataID`)
) ENGINE=InnoDB AUTO_INCREMENT=67665 DEFAULT CHARSET=utf8;

CREATE TABLE `tblEnvironmentalObservations` (
  `EnvObservationID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `ObservationGroup` varchar(50) DEFAULT NULL,
  `Observation` varchar(50) DEFAULT NULL,
  `ObservationSupp` varchar(50) DEFAULT NULL,
  `PipeSize_cm` int(10) DEFAULT NULL,
  `FishPassageObstructionInd` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`EnvObservationID`),
  UNIQUE KEY `EnvObservationID` (`EnvObservationID`),
  KEY `AquaticActivityID` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblEnvironmentalPlanning` (
  `EnvPlanningID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `IssueCategory` varchar(50) DEFAULT NULL,
  `Issue` varchar(250) DEFAULT NULL,
  `ActionRequired` varchar(250) DEFAULT NULL,
  `ActionTargetDate` datetime DEFAULT NULL,
  `ActionPriority` smallint(5) DEFAULT NULL,
  `ActionCompletionDate` datetime DEFAULT NULL,
  `FollowUpRequired` tinyint(1) NOT NULL DEFAULT '0',
  `FollowUpTargetDate` datetime DEFAULT NULL,
  `FollowUpCompletionDate` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`EnvPlanningID`),
  UNIQUE KEY `EnvPlanningID` (`EnvPlanningID`),
  KEY `AquaticActivityID` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblEnvironmentalSurveyFieldMeasures` (
  `FieldMeasureID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `StreamCover` varchar(10) DEFAULT NULL,
  `BankStability` varchar(20) DEFAULT NULL,
  `BankSlope_Rt` smallint(5) DEFAULT NULL,
  `BankSlope_Lt` smallint(5) DEFAULT NULL,
  `StreamType` varchar(10) DEFAULT NULL,
  `StreamTypeSupp` varchar(30) DEFAULT NULL,
  `SuspendedSilt` tinyint(1) NOT NULL DEFAULT '0',
  `EmbeddedSub` tinyint(1) NOT NULL DEFAULT '0',
  `AquaticPlants` tinyint(1) NOT NULL DEFAULT '0',
  `Algae` tinyint(1) NOT NULL DEFAULT '0',
  `Petroleum` tinyint(1) NOT NULL DEFAULT '0',
  `Odor` tinyint(1) NOT NULL DEFAULT '0',
  `Foam` tinyint(1) NOT NULL DEFAULT '0',
  `DeadFish` tinyint(1) NOT NULL DEFAULT '0',
  `Other` tinyint(1) NOT NULL DEFAULT '0',
  `OtherSupp` varchar(50) DEFAULT NULL,
  `Length_m` double(7,2) DEFAULT NULL,
  `AveWidth_m` double(7,2) DEFAULT NULL,
  `AveDepth_m` double(7,2) DEFAULT NULL,
  `Velocity_mpers` double(7,2) DEFAULT NULL,
  `WaterClarity` varchar(16) DEFAULT NULL,
  `WaterColor` varchar(10) DEFAULT NULL,
  `Weather_Past` varchar(20) DEFAULT NULL,
  `Weather_Current` varchar(20) DEFAULT NULL,
  `RZ_Lawn_Lt` smallint(5) DEFAULT NULL,
  `RZ_Lawn_Rt` double(7,2) DEFAULT NULL,
  `RZ_RowCrop_Lt` smallint(5) DEFAULT NULL,
  `RZ_RowCrop_Rt` smallint(5) DEFAULT NULL,
  `RZ_ForageCrop_Lt` smallint(5) DEFAULT NULL,
  `RZ_ForageCrop_Rt` smallint(5) DEFAULT NULL,
  `RZ_Shrubs_Lt` smallint(5) DEFAULT NULL,
  `RZ_Shrubs_Rt` smallint(5) DEFAULT NULL,
  `RZ_Hardwood_Lt` smallint(5) DEFAULT NULL,
  `RZ_Hardwood_Rt` smallint(5) DEFAULT NULL,
  `RZ_Softwood_Lt` smallint(5) DEFAULT NULL,
  `RZ_Softwood_Rt` smallint(5) DEFAULT NULL,
  `RZ_Mixed_Lt` smallint(5) DEFAULT NULL,
  `RZ_Mixed_Rt` smallint(5) DEFAULT NULL,
  `RZ_Meadow_Lt` smallint(5) DEFAULT NULL,
  `RZ_Meadow_Rt` smallint(5) DEFAULT NULL,
  `RZ_Wetland_Lt` smallint(5) DEFAULT NULL,
  `RZ_Wetland_Rt` smallint(5) DEFAULT NULL,
  `RZ_Altered_Lt` smallint(5) DEFAULT NULL,
  `RZ_Altered_Rt` smallint(5) DEFAULT NULL,
  `ST_TimeofDay` varchar(5) DEFAULT NULL,
  `ST_DissOxygen` double(7,2) DEFAULT NULL,
  `ST_AirTemp_C` double(7,2) DEFAULT NULL,
  `ST_WaterTemp_C` double(7,2) DEFAULT NULL,
  `ST_pH` double(7,2) DEFAULT NULL,
  `ST_Conductivity` double(7,2) DEFAULT NULL,
  `ST_Flow_cms` double(7,2) DEFAULT NULL,
  `ST_DELGFieldNo` varchar(50) DEFAULT NULL,
  `GW1_TimeofDay` varchar(5) DEFAULT NULL,
  `GW1_DissOxygen` double(7,2) DEFAULT NULL,
  `GW1_AirTemp_C` double(7,2) DEFAULT NULL,
  `GW1_WaterTemp_C` double(7,2) DEFAULT NULL,
  `GW1_pH` double(7,2) DEFAULT NULL,
  `GW1_Conductivity` double(7,2) DEFAULT NULL,
  `GW1_Flow_cms` double(7,2) DEFAULT NULL,
  `GW1_DELGFieldNo` varchar(50) DEFAULT NULL,
  `GW2_TimeofDay` varchar(5) DEFAULT NULL,
  `GW2_DissOxygen` double(7,2) DEFAULT NULL,
  `GW2_AirTemp_C` double(7,2) DEFAULT NULL,
  `GW2_WaterTemp_C` double(7,2) DEFAULT NULL,
  `GW2_pH` double(7,2) DEFAULT NULL,
  `GW2_Conductivity` double(7,2) DEFAULT NULL,
  `GW2_Flow_cms` double(7,2) DEFAULT NULL,
  `GW2_DELGFieldNo` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FieldMeasureID`),
  UNIQUE KEY `FieldMeasureID` (`FieldMeasureID`),
  KEY `AquaticActivityID` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblFishCount` (
  `FishCountID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `MovementDirection` varchar(4) DEFAULT NULL,
  `MovementTime` varchar(10) DEFAULT NULL,
  `FishSpeciesCd` varchar(3) DEFAULT NULL,
  `FishOrigin` varchar(10) DEFAULT NULL,
  `FishAgeClass` varchar(12) DEFAULT NULL,
  `RelativeSizeClass` varchar(10) DEFAULT NULL,
  `FishAge` varchar(5) DEFAULT NULL,
  `SexCd` varchar(1) DEFAULT NULL,
  `NoFish` int(10) DEFAULT NULL,
  `FishStatusCd` varchar(4) DEFAULT NULL,
  `RPM` double(15,5) DEFAULT NULL,
  `RPM Left_Right` varchar(16) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishCountID`),
  KEY `{06EA6C0C-673D-49A5-80FF-3F8553` (`FishSpeciesCd`),
  KEY `{5D7B660D-0861-4E5F-A43C-FEA1F6` (`SexCd`),
  KEY `{66BB9C3A-7285-4FDB-B4BC-DBCB50` (`AquaticActivityID`),
  KEY `{CAEC13B9-5CC5-4B2A-A167-36394C` (`FishStatusCd`),
  KEY `{E12AAD0E-8C73-403B-9564-76C09F` (`FishAgeClass`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`),
  KEY `FishCountID` (`FishCountID`)
) ENGINE=InnoDB AUTO_INCREMENT=46064 DEFAULT CHARSET=utf8;

CREATE TABLE `tblFishFacility` (
  `FishFacilityID` int(10) NOT NULL,
  `AquaticSiteID` int(10) DEFAULT NULL,
  `FishFacilityType` varchar(20) DEFAULT NULL,
  `FishFacilityCategory` varchar(20) DEFAULT NULL,
  `WaterBodyID` int(10) DEFAULT NULL,
  `FishFacilityName` varchar(50) DEFAULT NULL,
  `AgencyCd` varchar(4) DEFAULT NULL,
  `YearsActive` varchar(20) DEFAULT NULL,
  `ActiveInd` varchar(15) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishFacilityID`),
  KEY `{62AE88DB-B6DA-461A-8EFD-79994C` (`AgencyCd`),
  KEY `AquaticSiteID` (`AquaticSiteID`),
  KEY `FishFacilityID` (`FishFacilityID`),
  KEY `WaterBodyID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblFishMating` (
  `FishMatingID` int(10) NOT NULL AUTO_INCREMENT,
  `FishMating` varchar(150) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishMatingID`),
  KEY `Mating Code` (`FishMatingID`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;

CREATE TABLE `tblFishMeasurement` (
  `FishSampleID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `SweepNo` int(10) DEFAULT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `FishOrigin` varchar(1) DEFAULT NULL,
  `FishAge` varchar(255) DEFAULT NULL,
  `FishAgeClass` varchar(20) DEFAULT NULL,
  `RelativeSizeClass` varchar(6) DEFAULT NULL,
  `SexCd` varchar(4) DEFAULT NULL,
  `Maturity` varchar(50) DEFAULT NULL,
  `FishStatusCd` varchar(25) DEFAULT NULL,
  `FishMortalityCauseCd` int(10) DEFAULT NULL,
  `ForkLength_mm` double(15,5) DEFAULT NULL,
  `TotalLength_mm` double(15,5) DEFAULT NULL,
  `Weight_gm` double(15,5) DEFAULT NULL,
  `ObservedMarkCd` int(10) DEFAULT NULL,
  `ObservedTagTypeCd` varchar(255) DEFAULT NULL,
  `ObservedTagNo` varchar(255) DEFAULT NULL,
  `AppliedMarkCd` int(10) DEFAULT NULL,
  `AppliedTagTypeCd` varchar(255) DEFAULT NULL,
  `AppliedTagDetails` varchar(50) DEFAULT NULL,
  `AppliedTagNo` varchar(255) DEFAULT NULL,
  `ScaleSampleInd` varchar(1) DEFAULT NULL,
  `KFactor` varchar(255) DEFAULT NULL,
  `Comments` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishSampleID`),
  KEY `{3A73ACBD-5E01-4161-A005-936056` (`FishAgeClass`),
  KEY `{5789DFE0-E15C-4411-B206-AB85F6` (`ObservedMarkCd`),
  KEY `{78BF6931-900B-4BA0-9668-0F6ADF` (`FishStatusCd`),
  KEY `{B3899285-6946-4B56-8F15-8CC930` (`FishMortalityCauseCd`),
  KEY `{BAEC7ACC-1DA9-47D4-A524-136D1F` (`AppliedMarkCd`),
  KEY `{C8F34BD0-92BF-465C-9970-616E6A` (`FishSpeciesCd`),
  KEY `{F065211C-F778-44FD-9014-6CD26F` (`SexCd`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`)
) ENGINE=InnoDB AUTO_INCREMENT=285877 DEFAULT CHARSET=utf8;

CREATE TABLE `tblFishStock` (
  `FishStockID` int(10) NOT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `WaterBodyID` int(10) DEFAULT NULL,
  `FishStockName` varchar(150) DEFAULT NULL,
  `WildStatus` varchar(30) DEFAULT NULL,
  `RunSeason` varchar(10) DEFAULT NULL,
  `TriploidInd` tinyint(1) NOT NULL DEFAULT '0',
  `LandlockedInd` tinyint(1) NOT NULL DEFAULT '0',
  `FishFacilityID` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishStockID`),
  KEY `{9CC37BEE-D922-4454-8E9C-90F6EB` (`FishSpeciesCd`),
  KEY `FishFacilityID` (`FishFacilityID`),
  KEY `FishStockID` (`FishStockID`),
  KEY `WaterBodyID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblFishTranslocation` (
  `FishTranslocationID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `FishStockID` int(10) DEFAULT NULL,
  `FishAgeClass` varchar(6) DEFAULT NULL,
  `NoFish` double(15,5) DEFAULT NULL,
  `ForkLength_cm` double(15,5) DEFAULT NULL,
  `Weight_gm` double(15,5) DEFAULT NULL,
  `AppliedMarkCd` int(10) DEFAULT NULL,
  `AppliedTagNo` varchar(50) DEFAULT NULL,
  `Source` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishTranslocationID`),
  KEY `{197AEA6C-6EDA-4CDD-928E-AC3D74` (`FishAgeClass`),
  KEY `{3F66498F-954D-4260-B4DB-340DA6` (`FishStockID`),
  KEY `{C1A7EB34-A8A5-481B-A17D-074E4F` (`AppliedMarkCd`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `FishStockID` (`FishStockID`),
  KEY `FishTranslocationID` (`FishTranslocationID`),
  KEY `OldAquaticActivityID` (`TempAquaticActivityID`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8;

CREATE TABLE `tblHabitatRestoration` (
  `AquaticActivityID` int(10) NOT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `RestorationDesc` varchar(150) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityID`),
  KEY `{A405B266-7050-4183-B60D-3AFE5A` (`AquaticActivityID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `OldAquaticActivityID` (`TempAquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblHabitatUnit` (
  `HabitatUnitID` double(15,5) NOT NULL,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `RiverSystemID` smallint(5) DEFAULT NULL,
  `WaterBodyID` double(15,5) DEFAULT NULL,
  `WaterBodyName` varchar(40) DEFAULT NULL,
  `StartRouteMeas` double(15,5) DEFAULT NULL,
  `EndRouteMeas` double(15,5) DEFAULT NULL,
  `CalibratedLength_m` double(15,5) DEFAULT NULL,
  `StreamOrder` smallint(5) DEFAULT NULL,
  `ReachNo` smallint(5) DEFAULT NULL,
  `HabitatUnitNo` varchar(3) DEFAULT NULL,
  `StreamTypeCd` varchar(2) DEFAULT NULL,
  `ChannelCd` varchar(1) DEFAULT NULL,
  `ChannelPosition` varchar(1) DEFAULT NULL,
  `StreamLength_m` double(15,5) DEFAULT NULL,
  `WetWidth_m` double(15,5) DEFAULT NULL,
  `BankFullWidth_m` double(15,5) DEFAULT NULL,
  `Area_m2` double(15,5) DEFAULT NULL,
  `Bedrock` smallint(5) DEFAULT NULL,
  `Boulder` smallint(5) DEFAULT NULL,
  `Rock` smallint(5) DEFAULT NULL,
  `Rubble` smallint(5) DEFAULT NULL,
  `Gravel` smallint(5) DEFAULT NULL,
  `Sand` smallint(5) DEFAULT NULL,
  `Fines` smallint(5) DEFAULT NULL,
  `TotalLgSubstrate` smallint(5) DEFAULT NULL,
  `AveDepth_cm` smallint(5) DEFAULT NULL,
  `UndercutBank_L` smallint(5) DEFAULT NULL,
  `UndercutBank_R` smallint(5) DEFAULT NULL,
  `OverhangingVeg_L` smallint(5) DEFAULT NULL,
  `OverhangingVeg_R` smallint(5) DEFAULT NULL,
  `WoodyDebrisLength_m` double(15,5) DEFAULT NULL,
  `WoodyDebrisLengthPer100m2` double(15,5) DEFAULT NULL,
  `WaterSourceCd` varchar(1) DEFAULT NULL,
  `WaterFlow_cms` double(15,5) DEFAULT NULL,
  `AssmtTime` varchar(5) DEFAULT NULL,
  `WaterTemp_C` double(15,5) DEFAULT NULL,
  `AirTemp_C` double(15,5) DEFAULT NULL,
  `EmbeddedCd` varchar(1) DEFAULT NULL,
  `CommentCds` varchar(150) DEFAULT NULL,
  `Shade` smallint(5) DEFAULT NULL,
  `Bank_Bare` smallint(5) DEFAULT NULL,
  `Bank_Grass` smallint(5) DEFAULT NULL,
  `Bank_Shrubs` smallint(5) DEFAULT NULL,
  `Bank_Trees` smallint(5) DEFAULT NULL,
  `Bank_L_Stable` smallint(5) DEFAULT NULL,
  `Bank_L_BarelyStable` smallint(5) DEFAULT NULL,
  `Bank_L_Eroding` smallint(5) DEFAULT NULL,
  `Bank_R_Stable` smallint(5) DEFAULT NULL,
  `Bank_R_BarelyStable` smallint(5) DEFAULT NULL,
  `Bank_R_Eroding` smallint(5) DEFAULT NULL,
  `FieldNotes` varchar(250) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`HabitatUnitID`),
  KEY `{2C20CD7A-D76A-4B79-9722-A2169A` (`ChannelCd`),
  KEY `{4E89055D-2136-4D66-B94B-190547` (`EmbeddedCd`),
  KEY `{77627C39-5B81-431D-8AFC-2A560E` (`StreamTypeCd`),
  KEY `{AFB36345-F8C9-44B0-87E6-4C519B` (`AquaticActivityID`),
  KEY `{B40FC300-BC5B-4B37-B35E-421B87` (`WaterSourceCd`),
  KEY `{F8305F71-FA7B-4614-BD08-B115EB` (`RiverSystemID`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`),
  KEY `HABUNIT_ID` (`HabitatUnitID`),
  KEY `RiverSystemID` (`RiverSystemID`),
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblHabitatUnitComment` (
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `HabitatUnitID` double(15,5) DEFAULT NULL,
  `CommentCd` varchar(3) DEFAULT NULL,
  `Comment` varchar(30) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `{1D8D4C80-ED60-4F4D-AD66-AEFD1A` (`HabitatUnitID`),
  KEY `{CE25D1D9-753C-4839-A68F-C3A029` (`CommentCd`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`),
  KEY `HABUNIT_ID` (`HabitatUnitID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblHabitatUnitWaterMeasurement` (
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `HabitatUnitID` double(15,5) DEFAULT NULL,
  `WaterSourceCd` varchar(1) DEFAULT NULL,
  `AssmtTime` varchar(5) DEFAULT NULL,
  `WaterTemp_C` double(15,5) DEFAULT NULL,
  `AirTemp_C` double(15,5) DEFAULT NULL,
  `WaterFlow_cms` double(15,5) DEFAULT NULL,
  `WaterFlow_gpm` double(15,5) DEFAULT NULL,
  `WaterFlow_lpm` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `{597706DE-D7FA-4CD5-A07A-B86693` (`HabitatUnitID`),
  KEY `{930FC3B8-C2A8-4C09-B400-AED987` (`WaterSourceCd`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`),
  KEY `HABUNIT_ID` (`HabitatUnitID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblLakeAttribute` (
  `WaterBodyID` int(10) NOT NULL,
  `County` varchar(20) DEFAULT NULL,
  `Parish` varchar(30) DEFAULT NULL,
  `LakeClass` varchar(15) DEFAULT NULL,
  `Area_m2` double(15,5) DEFAULT NULL,
  `Perimeter_m` double(15,5) DEFAULT NULL,
  `ShorelineCrown_Percent` int(10) DEFAULT NULL,
  `ShorelinePrivate_Percent` int(10) DEFAULT NULL,
  `Depth_Max` double(15,5) DEFAULT NULL,
  `Depth_Mean` double(15,5) DEFAULT NULL,
  `Depth_Percent_LT6m` smallint(5) DEFAULT NULL,
  `Depth_Percent_LT3m` smallint(5) DEFAULT NULL,
  `StratifiedInd` varchar(2) DEFAULT NULL,
  `Volume_m3` double(15,5) DEFAULT NULL,
  `AcreFeet` double(15,5) DEFAULT NULL,
  `MEI` double(15,5) DEFAULT NULL,
  `PotentialProductivity` double(15,5) DEFAULT NULL,
  `WCHIndex` double(15,5) DEFAULT NULL,
  `SalmonIndex` double(15,5) DEFAULT NULL,
  `TogueIndex` double(15,5) DEFAULT NULL,
  `TotalProductivity` double(15,5) DEFAULT NULL,
  `ShorelineDev` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterBodyID`),
  UNIQUE KEY `{4E408586-E3BB-430C-BCE6-FAB4A7` (`WaterBodyID`),
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblLakeSurveyDetail` (
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `DNRRegion` varchar(1) DEFAULT NULL,
  `CountyCd` varchar(2) DEFAULT NULL,
  `County` varchar(20) DEFAULT NULL,
  `ParishCd` varchar(3) DEFAULT NULL,
  `PARISH` varchar(30) DEFAULT NULL,
  `AirTemp_F` smallint(5) DEFAULT NULL,
  `Terrain_Flat` smallint(5) DEFAULT NULL,
  `Terrain_Rolling` smallint(5) DEFAULT NULL,
  `Terrain_Hilly` smallint(5) DEFAULT NULL,
  `Terrain_Mountains` smallint(5) DEFAULT NULL,
  `Forest_Softwood` smallint(5) DEFAULT NULL,
  `Forest_Hardwood` smallint(5) DEFAULT NULL,
  `Forest_Soft_Hard` smallint(5) DEFAULT NULL,
  `Forest_Hard_Soft` smallint(5) DEFAULT NULL,
  `ShoreUse_Cutover` smallint(5) DEFAULT NULL,
  `ShoreUse_MatureTimber` smallint(5) DEFAULT NULL,
  `ShoreUse_ImmatureTimber` smallint(5) DEFAULT NULL,
  `ShoreUse_Residences` smallint(5) DEFAULT NULL,
  `ShoreUse_Cottages` smallint(5) DEFAULT NULL,
  `ShoreUse_Farms` smallint(5) DEFAULT NULL,
  `ShoreUse_Wetlands` smallint(5) DEFAULT NULL,
  `AquaticVeg_Submerged` smallint(5) DEFAULT NULL,
  `AquaticVeg_Emergent` smallint(5) DEFAULT NULL,
  `ShoreVeg_Sedge` smallint(5) DEFAULT NULL,
  `ShoreVeg_Heath` smallint(5) DEFAULT NULL,
  `ShoreVeg_Cedar` smallint(5) DEFAULT NULL,
  `ShoreVeg_Alder` smallint(5) DEFAULT NULL,
  `Substrate_Mud` smallint(5) DEFAULT NULL,
  `Substrate_Sand` smallint(5) DEFAULT NULL,
  `Substrate_Rubble` smallint(5) DEFAULT NULL,
  `Substrate_Gravel` smallint(5) DEFAULT NULL,
  `Substrate_Rock` smallint(5) DEFAULT NULL,
  `Substrate_Boulders` smallint(5) DEFAULT NULL,
  `Substrate_Bedrock` smallint(5) DEFAULT NULL,
  `PublicAccess_Trail` smallint(5) DEFAULT NULL,
  `PublicAccess_Car` smallint(5) DEFAULT NULL,
  `PublicAccess_Jeep` smallint(5) DEFAULT NULL,
  `PublicAccess_Boat` smallint(5) DEFAULT NULL,
  `PrivateAccess_Trail` smallint(5) DEFAULT NULL,
  `PrivateAccess_Car` smallint(5) DEFAULT NULL,
  `PrivateAccess_Jeep` smallint(5) DEFAULT NULL,
  `PrivateAccess_Boat` smallint(5) DEFAULT NULL,
  `NoBoatLandings` smallint(5) DEFAULT NULL,
  `ShoreOwnership_Crown` smallint(5) DEFAULT NULL,
  `ShoreOwnership_Private` smallint(5) DEFAULT NULL,
  `NoCamps` smallint(5) DEFAULT NULL,
  `NoBeaches` smallint(5) DEFAULT NULL,
  `WoodyDebris` varchar(14) DEFAULT NULL,
  `ShorelineShape` varchar(16) DEFAULT NULL,
  `SpawningPotential` varchar(4) DEFAULT NULL,
  `SecchiDepth_ft` smallint(5) DEFAULT NULL,
  `WaterColor` varchar(14) DEFAULT NULL,
  `WaterChemInd` varchar(1) DEFAULT NULL,
  `AnglingInfoInd` varchar(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `{5316EF9C-8A04-4E5D-9CB5-393792` (`AquaticActivityID`),
  KEY `ActivityID` (`AquaticActivityID`),
  KEY `oldAquaticActivityID` (`TempAquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblLakeSurveyFishSpecies` (
  `LakeSurveyFishID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `OldAssmtID` smallint(5) DEFAULT NULL,
  `HoursFished` smallint(5) DEFAULT NULL,
  `GearType` varchar(20) DEFAULT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `NoFish` smallint(5) DEFAULT NULL,
  `Length_Min` double(15,5) DEFAULT NULL,
  `Length_Max` double(15,5) DEFAULT NULL,
  `PopulationStatus` varchar(8) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`LakeSurveyFishID`),
  KEY `{83C4C015-3FED-4A6C-A4CA-11E735` (`AquaticActivityID`),
  KEY `{AC5B557E-7BBC-48AF-A07C-926CB9` (`FishSpeciesCd`),
  KEY `activityid` (`AquaticActivityID`),
  KEY `ASSMT_ID` (`OldAssmtID`),
  KEY `LakeSurveyFishID` (`LakeSurveyFishID`)
) ENGINE=InnoDB AUTO_INCREMENT=1442 DEFAULT CHARSET=utf8;

CREATE TABLE `tblLakeSurveyTribAssessment` (
  `LakeSurveyTribID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `OldAssmtID` smallint(5) DEFAULT NULL,
  `TributaryName` varchar(20) DEFAULT NULL,
  `SurveyLength_mi` double(15,5) DEFAULT NULL,
  `AveWidth_ft` smallint(5) DEFAULT NULL,
  `WaterLevel` varchar(8) DEFAULT NULL,
  `Silt` smallint(5) DEFAULT NULL,
  `Sand` smallint(5) DEFAULT NULL,
  `Gravel` smallint(5) DEFAULT NULL,
  `Rubble` smallint(5) DEFAULT NULL,
  `Rock` smallint(5) DEFAULT NULL,
  `Boulder` smallint(5) DEFAULT NULL,
  `Bedrock` smallint(5) DEFAULT NULL,
  `NurseryLength_ft` smallint(5) DEFAULT NULL,
  `NurseryWidth_ft` smallint(5) DEFAULT NULL,
  `NurseryQuality` smallint(5) DEFAULT NULL,
  `SpawningLength_ft` smallint(5) DEFAULT NULL,
  `SpawningWidth_ft` smallint(5) DEFAULT NULL,
  `SpawningQuality` smallint(5) DEFAULT NULL,
  `NoPools_LT3ftDeep` smallint(5) DEFAULT NULL,
  `NoPools_3to6ftDeep` smallint(5) DEFAULT NULL,
  `NoPools_GT6ftDeep` smallint(5) DEFAULT NULL,
  `ObstructionInd` varchar(1) DEFAULT NULL,
  `ObstructionType` varchar(10) DEFAULT NULL,
  `FishwayInd` varchar(1) DEFAULT NULL,
  `VerticalJump` smallint(5) DEFAULT NULL,
  `HorizontalJump` smallint(5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`LakeSurveyTribID`),
  KEY `{815C93E0-C509-47BE-939F-B306D3` (`AquaticActivityID`),
  KEY `activityID` (`AquaticActivityID`),
  KEY `ASSMT_ID` (`OldAssmtID`),
  KEY `LakeSurveyTribID` (`LakeSurveyTribID`)
) ENGINE=InnoDB AUTO_INCREMENT=640 DEFAULT CHARSET=utf8;

CREATE TABLE `tblLakeSurveyWaterMeasurement` (
  `LakeSurveyWaterMeasID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `OldAssmtID` smallint(5) DEFAULT NULL,
  `AirTemp` smallint(5) DEFAULT NULL,
  `SampleDepth` double(15,5) DEFAULT NULL,
  `WaterTemp_F` smallint(5) DEFAULT NULL,
  `DissolvedO2` double(15,5) DEFAULT NULL,
  `O2Saturation` double(15,5) DEFAULT NULL,
  `pH` double(15,5) DEFAULT NULL,
  `PhenoAlkalinity` double(15,5) DEFAULT NULL,
  `MethylOrangeAlkalinity` double(15,5) DEFAULT NULL,
  `TotalHardness` double(15,5) DEFAULT NULL,
  `CO2` double(15,5) DEFAULT NULL,
  `FreeAcid` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`LakeSurveyWaterMeasID`),
  KEY `{FCA583A3-894E-448B-8E19-1E2110` (`AquaticActivityID`),
  KEY `ACTIVITYID` (`AquaticActivityID`),
  KEY `ASSMT_ID` (`OldAssmtID`),
  KEY `FREE_ACID` (`FreeAcid`),
  KEY `LakeSurveyWaterMeasID` (`LakeSurveyWaterMeasID`)
) ENGINE=InnoDB AUTO_INCREMENT=1217 DEFAULT CHARSET=utf8;

CREATE TABLE `tblLevel1Basin` (
  `Level1No` varchar(2) NOT NULL,
  `Level1Name` varchar(40) DEFAULT NULL,
  `OceanName` varchar(20) DEFAULT NULL,
  `Area_km2` double(15,5) DEFAULT NULL,
  `Area_Percent` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`Level1No`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblObservations` (
  `ObservationID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `OandMCd` int(10) DEFAULT NULL,
  `OandM_Details` varchar(150) DEFAULT NULL,
  `OandMValuesCd` int(10) DEFAULT NULL,
  `FishPassageObstructionInd` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`ObservationID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `EnvSurveyID` (`ObservationID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblOldHabitatSurvey` (
  `HabitatSurveyID` int(10) NOT NULL AUTO_INCREMENT,
  `WaterBodyID` double(15,5) DEFAULT NULL,
  `AgencyCd` varchar(4) DEFAULT NULL,
  `SectionNo` smallint(5) DEFAULT NULL,
  `SectionDesc` varchar(50) DEFAULT NULL,
  `StreamLength_m` double(15,5) DEFAULT NULL,
  `AveWidth_m` double(15,5) DEFAULT NULL,
  `Area_m2` double(15,5) DEFAULT NULL,
  `ProductiveArea` double(15,5) DEFAULT NULL,
  `NonProductiveArea_m2` double(15,5) DEFAULT NULL,
  `GoodArea_m2` double(15,5) DEFAULT NULL,
  `FairArea_m2` double(15,5) DEFAULT NULL,
  `PoorArea_m2` double(15,5) DEFAULT NULL,
  `FieldNotes` varchar(150) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`HabitatSurveyID`),
  KEY `HabitatSurveyID` (`HabitatSurveyID`),
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB AUTO_INCREMENT=268 DEFAULT CHARSET=utf8;

CREATE TABLE `tblPhotos` (
  `PhotoID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `Path` varchar(50) DEFAULT NULL,
  `FileName` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`PhotoID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `PhotoID` (`PhotoID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblReconnaissanceResult` (
  `AquaticActivityID` int(10) NOT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `StreamTypeCd` varchar(2) DEFAULT NULL,
  `WetWidth_m` double(15,5) DEFAULT NULL,
  `BankFullWidth_m` double(15,5) DEFAULT NULL,
  `Bedrock` smallint(5) DEFAULT NULL,
  `Boulder` smallint(5) DEFAULT NULL,
  `Rock` smallint(5) DEFAULT NULL,
  `Rubble` smallint(5) DEFAULT NULL,
  `Gravel` smallint(5) DEFAULT NULL,
  `Sand` smallint(5) DEFAULT NULL,
  `Fines` smallint(5) DEFAULT NULL,
  `EmbeddedCd` varchar(1) DEFAULT NULL,
  `AssmtTime` varchar(4) DEFAULT NULL,
  `AirTemp_C` double(15,5) DEFAULT NULL,
  `WaterTemp_C` double(15,5) DEFAULT NULL,
  `WaterFlow_cms` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityID`),
  KEY `{A1DC03BD-AD41-48A5-BE14-D25FF1` (`StreamTypeCd`),
  KEY `{D8682845-4751-4B5D-BC5F-C5F964` (`EmbeddedCd`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `oldAquaticActivityID` (`TempAquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblReddCount` (
  `AquaticActivityID` int(10) NOT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `NoSmallRedds` double(15,5) DEFAULT NULL,
  `NoLargeRedds` double(15,5) DEFAULT NULL,
  `TotalRedds` double(15,5) DEFAULT NULL,
  `NoGrilse` double(15,5) DEFAULT NULL,
  `NoMSW` double(15,5) DEFAULT NULL,
  `TotalASalmon` double(15,5) DEFAULT NULL,
  `Comments` varchar(150) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityID`),
  KEY `{222C0077-C2AF-4260-A81C-E9A777` (`AquaticActivityID`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblRegulatedWater` (
  `RegulatedWaterID` int(10) NOT NULL AUTO_INCREMENT,
  `WaterBodyID` int(10) DEFAULT NULL,
  `WaterBodyName` varchar(50) DEFAULT NULL,
  `RegulatedWaterName` varchar(50) DEFAULT NULL,
  `RegulationType` varchar(20) DEFAULT NULL,
  `RegulatedWaterCategory` varchar(20) DEFAULT NULL,
  `RegulatedWaterType` varchar(20) DEFAULT NULL,
  `SectionDes` varchar(255) DEFAULT NULL,
  `IncludesTribuaryInd` varchar(1) DEFAULT NULL,
  `StartDate` varchar(10) DEFAULT NULL,
  `EndDate` varchar(10) DEFAULT NULL,
  `StartDate2` varchar(10) DEFAULT NULL,
  `EndDate2` varchar(10) DEFAULT NULL,
  `StartYear` varchar(10) DEFAULT NULL,
  `EndYear` varchar(10) DEFAULT NULL,
  `ActiveInd` varchar(1) DEFAULT NULL,
  `Robins Comments` varchar(250) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`RegulatedWaterID`),
  KEY `ID` (`RegulatedWaterID`),
  KEY `WaterBodyID` (`WaterBodyID`)
) ENGINE=InnoDB AUTO_INCREMENT=320 DEFAULT CHARSET=utf8;

CREATE TABLE `tblRegulatedWaterStretch` (
  `RegWaterStretchID` int(10) NOT NULL AUTO_INCREMENT,
  `RegulatedWaterID` int(10) DEFAULT NULL,
  `RegulatedWaterName` varchar(50) DEFAULT NULL,
  `RegulationType` varchar(20) DEFAULT NULL,
  `RegulatedWaterCategory` varchar(20) DEFAULT NULL,
  `RegulatedWaterType` varchar(20) DEFAULT NULL,
  `SectionDesc` varchar(255) DEFAULT NULL,
  `WaterBodyID` int(10) DEFAULT NULL,
  `StartRouteMeas` double(15,5) DEFAULT NULL,
  `EndRouteMeas` double(15,5) DEFAULT NULL,
  `StreamLength_m` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`RegWaterStretchID`),
  KEY `{A1CB7636-57E5-40DC-994A-E5480B` (`WaterBodyID`),
  KEY `{C115ED9E-8DC5-4E4E-9FD3-028E51` (`RegulatedWaterID`),
  KEY `ID` (`RegWaterStretchID`),
  KEY `RegWaterID` (`RegulatedWaterID`),
  KEY `WaterBodyID` (`WaterBodyID`)
) ENGINE=InnoDB AUTO_INCREMENT=320 DEFAULT CHARSET=utf8;

CREATE TABLE `tblRelatedAquaticActivities` (
  `RelatedAquaticActivitiesID` int(10) NOT NULL AUTO_INCREMENT,
  `PrimaryAquaticActivityID` int(10) DEFAULT NULL,
  `RelatedAquaticActivityID` int(10) DEFAULT NULL,
  `oldPrimaryAquaticActivityID` int(10) DEFAULT NULL,
  `oldRelatedAquaticActivityID` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`RelatedAquaticActivitiesID`),
  KEY `AquaticActivityID` (`oldPrimaryAquaticActivityID`),
  KEY `oldRelatedAquaticActivityID` (`oldRelatedAquaticActivityID`),
  KEY `PrimaryAquaticActivityID` (`PrimaryAquaticActivityID`),
  KEY `RelatedAquaticActivityID` (`RelatedAquaticActivitiesID`),
  KEY `RelatedAquaticActivityID1` (`RelatedAquaticActivityID`)
) ENGINE=InnoDB AUTO_INCREMENT=1031 DEFAULT CHARSET=utf8;

CREATE TABLE `tblRiverSystem` (
  `RiverSystemID` smallint(5) NOT NULL,
  `WaterBodyID` int(10) DEFAULT NULL,
  `RiverSystemName` varchar(40) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`RiverSystemID`),
  KEY `RiverSystemID` (`RiverSystemID`),
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblSample` (
  `SampleID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `LabNo` varchar(10) DEFAULT NULL,
  `AgencySampleNo` varchar(10) DEFAULT NULL,
  `SampleDepth_m` double(7,2) DEFAULT NULL,
  `WaterSourceType` varchar(20) DEFAULT NULL,
  `SampleCollectionMethodCd` int(10) DEFAULT NULL,
  `AnalyzedBy` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SampleID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `cdSampleCollectionMethodtblSamp` (`SampleCollectionMethodCd`),
  KEY `tblAquaticActivitytblSample` (`AquaticActivityID`),
  KEY `tblSampleWaterSourceType` (`WaterSourceType`),
  KEY `TempAquaticActivityID` (`TempAquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblSatelliteRearing` (
  `AquaticActivityID` int(10) NOT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `NoTanks` smallint(5) DEFAULT NULL,
  `AgeClassReceived` varchar(15) DEFAULT NULL,
  `NoReceived` int(10) DEFAULT NULL,
  `DateStocked` varchar(10) DEFAULT NULL,
  `NoStocked` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`AquaticActivityID`),
  KEY `{63E3F53B-740C-4E97-82E7-710E46` (`AquaticActivityID`),
  KEY `{B2F6C32C-EB8E-47D5-ABD1-9D0EB5` (`AgeClassReceived`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblSiteMeasurement` (
  `SiteMeasurementID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `OandMCd` int(10) DEFAULT NULL,
  `OandM_Other` varchar(20) DEFAULT NULL,
  `Bank` varchar(10) DEFAULT NULL,
  `InstrumentCd` int(10) DEFAULT NULL,
  `Measurement` double(15,5) DEFAULT NULL,
  `UnitofMeasureCd` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SiteMeasurementID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `SiteMeasurementID` (`SiteMeasurementID`),
  KEY `tblAquaticActivitytblSiteMeasur` (`AquaticActivityID`)
) ENGINE=InnoDB AUTO_INCREMENT=5135 DEFAULT CHARSET=utf8;

CREATE TABLE `tblSpawners` (
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `SmallRedds` double(15,5) DEFAULT NULL,
  `LargeRedds` double(15,5) DEFAULT NULL,
  `TotalRedds` double(15,5) DEFAULT NULL,
  `NoGrilse` double(15,5) DEFAULT NULL,
  `NoMSW` double(15,5) DEFAULT NULL,
  `TotalASalmon` double(15,5) DEFAULT NULL,
  `Comments` varchar(150) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `AquaticActivityID1` (`TempAquaticActivityID`),
  KEY `AquaticActivityID2` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblSportfishingAnglingLease` (
  `SportfishingID` int(10) NOT NULL AUTO_INCREMENT,
  `RegulatedWaterID` int(10) DEFAULT NULL,
  `LeaseNo` smallint(5) DEFAULT NULL,
  `Year` varchar(4) DEFAULT NULL,
  `TB_TS_RodDay` double(15,5) DEFAULT NULL,
  `TB_TS_RodHours` int(10) DEFAULT NULL,
  `TB_Gr_Harvest` double(15,5) DEFAULT NULL,
  `TB_Gr_Release` double(15,5) DEFAULT NULL,
  `TB_Gr_Total` double(15,5) DEFAULT NULL,
  `TB_MSW_Harvest` double(15,5) DEFAULT NULL,
  `TB_MSW_Release` double(15,5) DEFAULT NULL,
  `TB_MSW_Total` double(15,5) DEFAULT NULL,
  `TB_AS_Harvest` double(15,5) DEFAULT NULL,
  `TB_AS_Release` double(15,5) DEFAULT NULL,
  `TB_AS_Total` double(15,5) DEFAULT NULL,
  `TB_CPU_Grilse` double(15,5) DEFAULT NULL,
  `TB_CPU_MSW` double(15,5) DEFAULT NULL,
  `TB_CPU_Total` double(15,5) DEFAULT NULL,
  `TS_BT_RodDay` double(15,5) DEFAULT NULL,
  `TS_BT_Harvest` double(15,5) DEFAULT NULL,
  `TS_BT_Release` double(15,5) DEFAULT NULL,
  `TS_BT_Total` double(15,5) DEFAULT NULL,
  `TS_CPU_BrookTrout` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SportfishingID`),
  KEY `{30865C15-4322-4026-86DB-C859C8` (`RegulatedWaterID`),
  KEY `LEASE_ID` (`LeaseNo`),
  KEY `RegulatedWaterID` (`RegulatedWaterID`)
) ENGINE=InnoDB AUTO_INCREMENT=513 DEFAULT CHARSET=utf8;

CREATE TABLE `tblSportfishingAtlanticSalmon` (
  `SportfishingID` int(10) NOT NULL AUTO_INCREMENT,
  `WaterBodyID` int(10) DEFAULT NULL,
  `WaterBodyName` varchar(55) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `Year` varchar(4) DEFAULT NULL,
  `KT_AS_RodDay` double(15,5) DEFAULT NULL,
  `KT_Gr_Harvest` double(15,5) DEFAULT NULL,
  `KT_Gr_Release` double(15,5) DEFAULT NULL,
  `KT_Gr_Total` double(15,5) DEFAULT NULL,
  `KT_MSW_Harvest` double(15,5) DEFAULT NULL,
  `KT_MSW_Release` double(15,5) DEFAULT NULL,
  `KT_MSW_Total` double(15,5) DEFAULT NULL,
  `KT_AS_Harvest` double(15,5) DEFAULT NULL,
  `KT_AS_Release` double(15,5) DEFAULT NULL,
  `KT_AS_Total` double(15,5) DEFAULT NULL,
  `KT_CPU_Grilse` double(15,5) DEFAULT NULL,
  `KT_CPU_MSW` double(15,5) DEFAULT NULL,
  `KT_CPU_Total` double(15,5) DEFAULT NULL,
  `KT_CPA_Lwr` double(15,5) DEFAULT NULL,
  `KT_CPA_Mean` double(15,5) DEFAULT NULL,
  `KT_CPA_Upr` double(15,5) DEFAULT NULL,
  `KT_CPA_CV` double(15,5) DEFAULT NULL,
  `TB_AS_RodDay` double(15,5) DEFAULT NULL,
  `TB_Gr_Harvest` double(15,5) DEFAULT NULL,
  `TB_Gr_Release` double(15,5) DEFAULT NULL,
  `TB_Gr_Total` double(15,5) DEFAULT NULL,
  `TB_MSW_Harvest` double(15,5) DEFAULT NULL,
  `TB_MSW_Release` double(15,5) DEFAULT NULL,
  `TB_MSW_Total` double(15,5) DEFAULT NULL,
  `TB_AS_Harvest` double(15,5) DEFAULT NULL,
  `TB_AS_Release` double(15,5) DEFAULT NULL,
  `TB_AS_Total` double(15,5) DEFAULT NULL,
  `TB_CPU_Grilse` double(15,5) DEFAULT NULL,
  `TB_CPU_MSW` double(15,5) DEFAULT NULL,
  `TB_CPU_Total` double(15,5) DEFAULT NULL,
  `TB_CPA_Lwr` double(15,5) DEFAULT NULL,
  `TB_CPA_Mean` double(15,5) DEFAULT NULL,
  `TB_CPA_Upr` double(15,5) DEFAULT NULL,
  `TB_CPA_CV` double(15,5) DEFAULT NULL,
  `EB_AS_RodDay` double(15,5) DEFAULT NULL,
  `EB_Gr_Harvest` double(15,5) DEFAULT NULL,
  `EB_Gr_Release` double(15,5) DEFAULT NULL,
  `EB_Gr_Total` double(15,5) DEFAULT NULL,
  `EB_MSW_Harvest` double(15,5) DEFAULT NULL,
  `EB_MSW_Release` double(15,5) DEFAULT NULL,
  `EB_MSW_Total` double(15,5) DEFAULT NULL,
  `EB_AS_Harvest` double(15,5) DEFAULT NULL,
  `EB_AS_Release` double(15,5) DEFAULT NULL,
  `EB_AS_Total` double(15,5) DEFAULT NULL,
  `EB_CPU_Grilse` double(15,5) DEFAULT NULL,
  `EB_CPU_MSW` double(15,5) DEFAULT NULL,
  `EB_CPU_Total` double(15,5) DEFAULT NULL,
  `LB_AS_RodDay` double(15,5) DEFAULT NULL,
  `LB_Gr_Harvest` double(15,5) DEFAULT NULL,
  `LB_Gr_Release` double(15,5) DEFAULT NULL,
  `LB_Gr_Total` double(15,5) DEFAULT NULL,
  `LB_MSW_Harvest` double(15,5) DEFAULT NULL,
  `LB_MSW_Release` double(15,5) DEFAULT NULL,
  `LB_MSW_Total` double(15,5) DEFAULT NULL,
  `LB_AS_Harvest` double(15,5) DEFAULT NULL,
  `LB_AS_Release` double(15,5) DEFAULT NULL,
  `LB_AS_Total` double(15,5) DEFAULT NULL,
  `LB_CPU_Grilse` double(15,5) DEFAULT NULL,
  `LB_CPU_MSW` double(15,5) DEFAULT NULL,
  `LB_CPU_Total` double(15,5) DEFAULT NULL,
  `TS_AS_RodDay` double(15,5) DEFAULT NULL,
  `TS_Gr_Harvest` double(15,5) DEFAULT NULL,
  `TS_Gr_Release` double(15,5) DEFAULT NULL,
  `TS_Gr_Total` double(15,5) DEFAULT NULL,
  `TS_MSW_Harvest` double(15,5) DEFAULT NULL,
  `TS_MSW_Release` double(15,5) DEFAULT NULL,
  `TS_MSW_Total` double(15,5) DEFAULT NULL,
  `TS_AS_Harvest` double(15,5) DEFAULT NULL,
  `TS_AS_Release` double(15,5) DEFAULT NULL,
  `TS_AS_Total` double(15,5) DEFAULT NULL,
  `TS_CPU_Grilse` double(15,5) DEFAULT NULL,
  `TS_CPU_MSW` double(15,5) DEFAULT NULL,
  `TS_CPU_Total` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SportfishingID`),
  KEY `{B2264753-0653-48B6-93B6-759023` (`WaterBodyID`),
  KEY `SportfishingID` (`SportfishingID`),
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB AUTO_INCREMENT=1338 DEFAULT CHARSET=utf8;

CREATE TABLE `tblSportfishingCrownReserve` (
  `SportfishingID` int(10) NOT NULL AUTO_INCREMENT,
  `RegulatedWaterID` int(10) DEFAULT NULL,
  `Year` varchar(4) DEFAULT NULL,
  `TB_TS_RodDay` double(15,5) DEFAULT NULL,
  `TB_Gr_Harvest` double(15,5) DEFAULT NULL,
  `TB_Gr_Release` double(15,5) DEFAULT NULL,
  `TB_Gr_Total` double(15,5) DEFAULT NULL,
  `TB_MSW_Harvest` double(15,5) DEFAULT NULL,
  `TB_MSW_Release` double(15,5) DEFAULT NULL,
  `TB_MSW_Total` double(15,5) DEFAULT NULL,
  `TB_AS_Harvest` double(15,5) DEFAULT NULL,
  `TB_AS_Release` double(15,5) DEFAULT NULL,
  `TB_AS_Total` double(15,5) DEFAULT NULL,
  `TB_CPU_Grilse` double(15,5) DEFAULT NULL,
  `TB_CPU_MSW` double(15,5) DEFAULT NULL,
  `TB_CPU_Total` double(15,5) DEFAULT NULL,
  `TS_BT_Harvest` double(15,5) DEFAULT NULL,
  `TS_BT_Release` double(15,5) DEFAULT NULL,
  `TS_BT_Total` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`SportfishingID`),
  KEY `{771658EA-10AB-4276-AE7C-A4A7E0` (`RegulatedWaterID`),
  KEY `RegulatedWaterID` (`RegulatedWaterID`),
  KEY `SportfishingID` (`SportfishingID`)
) ENGINE=InnoDB AUTO_INCREMENT=709 DEFAULT CHARSET=utf8;

CREATE TABLE `tblStockedFish` (
  `FishStockingID` int(10) NOT NULL AUTO_INCREMENT,
  `siteuseid` int(10) DEFAULT NULL,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `FishSpeciesCd` varchar(2) DEFAULT NULL,
  `FishStockID` int(10) DEFAULT NULL,
  `OtherStock` varchar(50) DEFAULT NULL,
  `FishMatingID` int(10) DEFAULT NULL,
  `FishStrainCd` int(10) DEFAULT NULL,
  `BroodstockInd` tinyint(1) NOT NULL DEFAULT '0',
  `FishAge` varchar(10) DEFAULT NULL,
  `AgeUnitOfMeasure` varchar(10) DEFAULT NULL,
  `FishAgeClass` varchar(20) DEFAULT NULL,
  `NoFish` int(10) DEFAULT NULL,
  `FishFacilityID` int(10) DEFAULT NULL,
  `OtherFishFacility` varchar(50) DEFAULT NULL,
  `FishTankNo` varchar(2) DEFAULT NULL,
  `SatelliteRearedInd` tinyint(1) NOT NULL DEFAULT '0',
  `AveLength_cm` double(15,5) DEFAULT NULL,
  `LengthRange_cm` varchar(20) DEFAULT NULL,
  `FishLengthType` varchar(10) DEFAULT NULL,
  `AveWeight_gm` double(15,5) DEFAULT NULL,
  `WeightRange_gm` varchar(20) DEFAULT NULL,
  `NoFishMeasured` int(10) DEFAULT NULL,
  `AppliedMarkCd` int(10) DEFAULT NULL,
  `Source` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`FishStockingID`),
  KEY `{42C7EB4F-0D16-4C9E-B72B-E3FAFE` (`FishStockID`),
  KEY `{4664ED76-C4C5-4F01-94C2-787706` (`FishMatingID`),
  KEY `{69365FA7-DC11-4323-8B3A-9B41CC` (`FishSpeciesCd`),
  KEY `{98DE86FF-08D4-4803-B4A0-6BBE0E` (`AppliedMarkCd`),
  KEY `{AA01333A-8722-46C3-8FD4-2BF486` (`FishFacilityID`),
  KEY `{BC3A6A6A-7068-4DFD-8F21-E0E9B8` (`FishAgeClass`),
  KEY `{DA7ACC03-F95D-442C-934E-76D801` (`AquaticActivityID`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`),
  KEY `FishMatingID` (`FishMatingID`),
  KEY `FishRearingFacilID` (`FishFacilityID`),
  KEY `FishStockID` (`FishStockID`),
  KEY `FishStockingID` (`FishStockingID`),
  KEY `siteuseid` (`siteuseid`)
) ENGINE=InnoDB AUTO_INCREMENT=28144 DEFAULT CHARSET=utf8;

CREATE TABLE `tblStreamAttribute` (
  `WaterBodyID` int(10) NOT NULL,
  `StreamLength_km` double(15,5) DEFAULT NULL,
  `HighestOrder` smallint(5) DEFAULT NULL,
  `IntermittentInd` varchar(1) DEFAULT NULL,
  `TidalInd` varchar(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterBodyID`),
  UNIQUE KEY `{A520FBFB-F9B2-44B6-99D7-0C8E1B` (`WaterBodyID`),
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblVibertBoxAnalysis` (
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `LocationDesc` varchar(20) DEFAULT NULL,
  `LidDepth_cm` double(15,5) DEFAULT NULL,
  `WetWeight_Initial_gm` double(15,5) DEFAULT NULL,
  `WetWeight_Final_gm` double(15,5) DEFAULT NULL,
  `WetWeight_Net_gm` double(15,5) DEFAULT NULL,
  `WetWeight_Fines_Percent` double(15,5) DEFAULT NULL,
  `DryWeight_Total_gm` double(15,5) DEFAULT NULL,
  `DrytWeight_Box_Rocks_gm` double(15,5) DEFAULT NULL,
  `DryWeight_Box_Rocks_Percent` double(15,5) DEFAULT NULL,
  `DryWeight_FineGravel_gm` double(15,5) DEFAULT NULL,
  `DryWeight_fineGravel_Percent` double(15,5) DEFAULT NULL,
  `DryWeight_Sand_gm` double(15,5) DEFAULT NULL,
  `DryWeight_Sand_Percent` double(15,5) DEFAULT NULL,
  `DryWeight_Fines_gm` double(15,5) DEFAULT NULL,
  `DryWeight_Fines_Percent` double(15,5) DEFAULT NULL,
  `Comments` varchar(150) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `oldAquaticActivityID` (`TempAquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblWaterBody` (
  `WaterBodyID` int(10) NOT NULL AUTO_INCREMENT,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `WaterBodyTypeCd` varchar(4) DEFAULT NULL,
  `WaterBodyName` varchar(55) DEFAULT NULL,
  `WaterBodyName_Abrev` varchar(40) DEFAULT NULL,
  `WaterBodyName_Alt` varchar(40) DEFAULT NULL,
  `WaterBodyComplexID` smallint(5) DEFAULT NULL,
  `Surveyed_Ind` varchar(1) DEFAULT NULL,
  `FlowsIntoWaterBodyID` double(15,5) DEFAULT NULL,
  `FlowsIntoWaterBodyName` varchar(40) DEFAULT NULL,
  `FlowIntoDrainageCd` varchar(17) DEFAULT NULL,
  `DateEntered` datetime DEFAULT NULL,
  `DateModified` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterBodyID`),
  KEY `{267293E5-26E7-418B-9AFA-318DAE` (`WaterBodyComplexID`),
  KEY `CMPLX_ID` (`WaterBodyComplexID`),
  KEY `DR_CODE` (`DrainageCd`),
  KEY `FLOW_ID` (`FlowsIntoWaterBodyID`),
  KEY `WATER_ID` (`WaterBodyID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000000 DEFAULT CHARSET=utf8;

CREATE TABLE `tblWaterBodyComplex` (
  `WaterBodyComplexID` smallint(5) NOT NULL,
  `WaterBodyComplexName` varchar(55) DEFAULT NULL,
  `WaterBodyComplexType` varchar(4) DEFAULT NULL,
  `DrainageCd` varchar(17) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterBodyComplexID`),
  KEY `CMPLX_ID` (`WaterBodyComplexID`),
  KEY `tblWaterBodyComplexesDrainageCd` (`DrainageCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblWaterChemistryAnalysis` (
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `DOE_Program` varchar(14) DEFAULT NULL,
  `DOE_ProjectNo` varchar(10) DEFAULT NULL,
  `DOE_StationNo` varchar(15) DEFAULT NULL,
  `DOE_LabNo` varchar(8) DEFAULT NULL,
  `DOE_FieldNo` varchar(11) DEFAULT NULL,
  `SecchiDepth_m` double(15,5) DEFAULT NULL,
  `SampleDepth_m` double(15,5) DEFAULT NULL,
  `WaterTemp_C` double(15,5) DEFAULT NULL,
  `DO` double(15,5) DEFAULT NULL,
  `TOXIC_UNIT` double(15,5) DEFAULT NULL,
  `L_HARD` varchar(1) DEFAULT NULL,
  `HARD` double(15,5) DEFAULT NULL,
  `NO3` double(15,5) DEFAULT NULL,
  `L_AL_X` varchar(1) DEFAULT NULL,
  `AL_X` double(15,5) DEFAULT NULL,
  `L_AL_XGF` varchar(1) DEFAULT NULL,
  `AL_XGF` double(15,5) DEFAULT NULL,
  `L_ALK_G` varchar(1) DEFAULT NULL,
  `ALK_G` double(15,5) DEFAULT NULL,
  `L_ALK_P` varchar(1) DEFAULT NULL,
  `ALK_P` double(15,5) DEFAULT NULL,
  `L_ALK_T` varchar(1) DEFAULT NULL,
  `ALK_T` double(15,5) DEFAULT NULL,
  `L_AS_XGF` varchar(1) DEFAULT NULL,
  `AS_XGF` double(15,5) DEFAULT NULL,
  `L_BA_X` varchar(1) DEFAULT NULL,
  `BA_X` double(15,5) DEFAULT NULL,
  `L_B_X` varchar(1) DEFAULT NULL,
  `B_X` double(15,5) DEFAULT NULL,
  `L_BR` varchar(1) DEFAULT NULL,
  `BR` double(15,5) DEFAULT NULL,
  `L_CA_D` varchar(1) DEFAULT NULL,
  `CA_D` double(15,5) DEFAULT NULL,
  `L_CD_XGF` varchar(1) DEFAULT NULL,
  `CD_XGF` double(15,5) DEFAULT NULL,
  `L_CHL_A` varchar(1) DEFAULT NULL,
  `CHL_A` double(15,5) DEFAULT NULL,
  `L_CL` varchar(1) DEFAULT NULL,
  `CL` double(15,5) DEFAULT NULL,
  `L_CL_IC` varchar(1) DEFAULT NULL,
  `CL_IC` double(15,5) DEFAULT NULL,
  `L_CLRA` varchar(1) DEFAULT NULL,
  `CLRA` double(15,5) DEFAULT NULL,
  `L_CO_X` varchar(1) DEFAULT NULL,
  `CO_X` double(15,5) DEFAULT NULL,
  `L_COND` varchar(1) DEFAULT NULL,
  `COND` double(15,5) DEFAULT NULL,
  `COND2` double(15,5) DEFAULT NULL,
  `L_CR_X` varchar(1) DEFAULT NULL,
  `CR_X` double(15,5) DEFAULT NULL,
  `L_CR_XGF` varchar(1) DEFAULT NULL,
  `CR_XGF` double(15,5) DEFAULT NULL,
  `L_CU_X` varchar(1) DEFAULT NULL,
  `CU_X` double(15,5) DEFAULT NULL,
  `L_CU_XGF` varchar(1) DEFAULT NULL,
  `CU_XGF` double(15,5) DEFAULT NULL,
  `L_DOC` varchar(1) DEFAULT NULL,
  `DOC` double(15,5) DEFAULT NULL,
  `L_F` varchar(1) DEFAULT NULL,
  `F` double(15,5) DEFAULT NULL,
  `L_FE_X` varchar(1) DEFAULT NULL,
  `FE_X` double(15,5) DEFAULT NULL,
  `L_HG_T` varchar(1) DEFAULT NULL,
  `HG_T` double(15,5) DEFAULT NULL,
  `L_K` varchar(1) DEFAULT NULL,
  `K` double(15,5) DEFAULT NULL,
  `L_MG_D` varchar(1) DEFAULT NULL,
  `MG_D` double(15,5) DEFAULT NULL,
  `L_MN_X` varchar(1) DEFAULT NULL,
  `MN_X` double(15,5) DEFAULT NULL,
  `L_NA` varchar(1) DEFAULT NULL,
  `NA` double(15,5) DEFAULT NULL,
  `L_NH3T` varchar(1) DEFAULT NULL,
  `NH3T` double(15,5) DEFAULT NULL,
  `L_NI_X` varchar(1) DEFAULT NULL,
  `NI_X` double(15,5) DEFAULT NULL,
  `L_NO2D` varchar(1) DEFAULT NULL,
  `NO2D` double(15,5) DEFAULT NULL,
  `L_NOX` varchar(1) DEFAULT NULL,
  `NOX` double(15,5) DEFAULT NULL,
  `L_PB_XGF` varchar(1) DEFAULT NULL,
  `PB_XGF` double(15,5) DEFAULT NULL,
  `L_PH` varchar(1) DEFAULT NULL,
  `PH` double(15,5) DEFAULT NULL,
  `L_PH_GAL` varchar(1) DEFAULT NULL,
  `PH_GAL` double(15,5) DEFAULT NULL,
  `L_SB_XGF` varchar(1) DEFAULT NULL,
  `SB_XGF` double(15,5) DEFAULT NULL,
  `L_SE_XGF` varchar(1) DEFAULT NULL,
  `SE_XGF` double(15,5) DEFAULT NULL,
  `SILICA` double(15,5) DEFAULT NULL,
  `L_SO4` varchar(1) DEFAULT NULL,
  `SO4` double(15,5) DEFAULT NULL,
  `L_SO4_IC` varchar(1) DEFAULT NULL,
  `SO4_IC` double(15,5) DEFAULT NULL,
  `L_SS` varchar(1) DEFAULT NULL,
  `SS` double(15,5) DEFAULT NULL,
  `L_TDS` varchar(1) DEFAULT NULL,
  `TDS` double(15,5) DEFAULT NULL,
  `L_TKN` varchar(1) DEFAULT NULL,
  `TKN` double(15,5) DEFAULT NULL,
  `L_TL_XGF` varchar(1) DEFAULT NULL,
  `TL_XGF` double(15,5) DEFAULT NULL,
  `L_TOC` varchar(1) DEFAULT NULL,
  `TOC` double(15,5) DEFAULT NULL,
  `L_TP_L` varchar(1) DEFAULT NULL,
  `TP_L` double(15,5) DEFAULT NULL,
  `L_TURB` varchar(1) DEFAULT NULL,
  `TURB` double(15,5) DEFAULT NULL,
  `L_ZN_X` varchar(1) DEFAULT NULL,
  `ZN_X` double(15,5) DEFAULT NULL,
  `L_ZN_XGF` varchar(1) DEFAULT NULL,
  `ZN_XGF` double(15,5) DEFAULT NULL,
  `L_O_PHOS` varchar(1) DEFAULT NULL,
  `O_PHOS` double(15,5) DEFAULT NULL,
  `BICARB` double(15,5) DEFAULT NULL,
  `CARB` double(15,5) DEFAULT NULL,
  `SAT_PH` double(15,5) DEFAULT NULL,
  `SAT_NDX` double(15,5) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  KEY `{A84E8104-E838-4C00-8C7A-E4A3D7` (`AquaticActivityID`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tblWaterMeasurement` (
  `WaterMeasurementID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `TempAquaticActivityID` int(10) DEFAULT NULL,
  `TempDataID` int(10) DEFAULT NULL,
  `TemperatureLoggerID` int(10) DEFAULT NULL,
  `HabitatUnitID` int(10) DEFAULT NULL,
  `SampleID` int(10) DEFAULT NULL,
  `WaterSourceCd` varchar(50) DEFAULT NULL,
  `WaterDepth_m` double(7,2) DEFAULT NULL,
  `TimeofDay` varchar(5) DEFAULT NULL,
  `OandMCd` int(10) DEFAULT NULL,
  `InstrumentCd` int(10) DEFAULT NULL,
  `Measurement` double(7,2) DEFAULT NULL,
  `UnitofMeasureCd` int(10) DEFAULT NULL,
  `QualifierCd` varchar(20) DEFAULT NULL,
  `Comment` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`WaterMeasurementID`),
  KEY `AquaticActivityID` (`TempAquaticActivityID`),
  KEY `AquaticActivityID1` (`AquaticActivityID`),
  KEY `cdInstrumenttblWaterMeasurement` (`InstrumentCd`),
  KEY `cdOandMtblWaterMeasurement` (`OandMCd`),
  KEY `cdUnitofMeasuretblWaterMeasurem` (`UnitofMeasureCd`),
  KEY `cdWaterSourcetblWaterMeasurement` (`WaterSourceCd`),
  KEY `SampleID` (`SampleID`),
  KEY `tblAquaticActivitytblWaterMeasu` (`AquaticActivityID`),
  KEY `tblWaterMeasurementQualifierCd` (`QualifierCd`),
  KEY `TempDataID` (`TempDataID`),
  KEY `TemperatureLoggerID` (`TemperatureLoggerID`),
  KEY `WaterMeasurementID` (`WaterMeasurementID`)
) ENGINE=InnoDB AUTO_INCREMENT=194944 DEFAULT CHARSET=utf8;

CREATE TABLE `tblWaterTemperatureLoggerDetails` (
  `TemperatureLoggerID` int(10) NOT NULL AUTO_INCREMENT,
  `AquaticActivityID` int(10) DEFAULT NULL,
  `LoggerNo` varchar(20) DEFAULT NULL,
  `BrandName` varchar(30) DEFAULT NULL,
  `Model` varchar(20) DEFAULT NULL,
  `Resolution` varchar(20) DEFAULT NULL,
  `Accuracy` varchar(20) DEFAULT NULL,
  `TempRange_From` int(10) DEFAULT NULL,
  `TempRange_To` int(10) DEFAULT NULL,
  `DataFileName` varchar(75) DEFAULT NULL,
  `InstallationDate` varchar(10) DEFAULT NULL,
  `RemovalDate` varchar(10) DEFAULT NULL,
  `RecordingStartDate` varchar(10) DEFAULT NULL,
  `RecordingEndDate` varchar(10) DEFAULT NULL,
  `OutofWaterReadingsOccurred` tinyint(1) NOT NULL DEFAULT '0',
  `OutofWaterReadingsRemoved` tinyint(1) NOT NULL DEFAULT '0',
  `DistanceFromLeftBank_m` int(10) DEFAULT NULL,
  `DistanceFromRightBank_m` int(10) DEFAULT NULL,
  `WaterDepth_cm` int(10) DEFAULT NULL,
  `SampleInterval_min` double(7,2) DEFAULT NULL,
  `Install_WaterTemp_C` double(7,2) DEFAULT NULL,
  `Install_AirTemp_C` double(7,2) DEFAULT NULL,
  `Install_TimeofDay` varchar(5) DEFAULT NULL,
  `Removal_WaterTemp_C` double(7,2) DEFAULT NULL,
  `Removal_AirTemp_C` double(7,2) DEFAULT NULL,
  `Removal_TimeofDay` varchar(5) DEFAULT NULL,
  `WaterLevel_Install` varchar(10) DEFAULT NULL,
  `WaterLevel_Removal` varchar(10) DEFAULT NULL,
  `DateEntered` datetime DEFAULT NULL,
  `IncorporatedInd` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`TemperatureLoggerID`),
  UNIQUE KEY `TemperatureLoggerID` (`TemperatureLoggerID`),
  KEY `AquaticActivityID` (`AquaticActivityID`),
  KEY `LoggerID` (`LoggerNo`)
) ENGINE=InnoDB AUTO_INCREMENT=291 DEFAULT CHARSET=utf8;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `login` varchar(100) DEFAULT NULL,
  `email` varchar(30) DEFAULT NULL,
  `admin` tinyint(1) DEFAULT '0',
  `editor` tinyint(1) DEFAULT '0',
  `requesting_editor_priveleges` tinyint(1) DEFAULT '0',
  `crypted_password` varchar(40) DEFAULT NULL,
  `salt` varchar(40) DEFAULT NULL,
  `remember_token` varchar(255) DEFAULT NULL,
  `remember_token_expires_at` datetime DEFAULT NULL,
  `activation_code` varchar(40) DEFAULT NULL,
  `activated_at` datetime DEFAULT NULL,
  `password_reset_code` varchar(40) DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT '1',
  `agency_id` varchar(5) DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `area_of_interest_id` int(11) DEFAULT NULL,
  `language` varchar(2) DEFAULT 'en',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO schema_migrations (version) VALUES ('20080923163400');

INSERT INTO schema_migrations (version) VALUES ('20080923163659');

INSERT INTO schema_migrations (version) VALUES ('20080923163742');

INSERT INTO schema_migrations (version) VALUES ('20080923163935');

INSERT INTO schema_migrations (version) VALUES ('20080923163956');

INSERT INTO schema_migrations (version) VALUES ('20080923163973');

INSERT INTO schema_migrations (version) VALUES ('20080926150102');

INSERT INTO schema_migrations (version) VALUES ('20081008163622');

INSERT INTO schema_migrations (version) VALUES ('20081127150314');

INSERT INTO schema_migrations (version) VALUES ('20090909143559');

INSERT INTO schema_migrations (version) VALUES ('20091023181741');