SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `cdAquaticActivity` CHANGE COLUMN `AquaticActivityCd` `AquaticActivityCd` SMALLINT(5) NOT NULL AUTO_INCREMENT  ;

ALTER TABLE `cdAquaticActivityMethod` CHANGE COLUMN `AquaticMethodCd` `AquaticMethodCd` SMALLINT(5) NOT NULL AUTO_INCREMENT  ;

ALTER TABLE `cdOandM` CHANGE COLUMN `OandM_ValuesInd` `OandM_ValuesInd` TINYINT(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `OandM_DetailsInd` `OandM_DetailsInd` TINYINT(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `FishPassageInd` `FishPassageInd` TINYINT(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `BankInd` `BankInd` TINYINT(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `cdUnitofMeasure` CHANGE COLUMN `UnitofMeasureCd` `UnitofMeasureCd` INT(10) NOT NULL AUTO_INCREMENT  ;

ALTER TABLE `tblAquaticActivity` CHANGE COLUMN `AquaticActivityID` `AquaticActivityID` INT(10) NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `PrimaryActivityInd` `PrimaryActivityInd` TINYINT(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `IncorporatedInd` `IncorporatedInd` TINYINT(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tblAquaticSite` CHANGE COLUMN `IncorporatedInd` `IncorporatedInd` TINYINT(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tblAquaticSiteAgencyUse` CHANGE COLUMN `IncorporatedInd` `IncorporatedInd` TINYINT(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tblObservations` CHANGE COLUMN `FishPassageObstructionInd` `FishPassageObstructionInd` TINYINT(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tblWaterBody` CHANGE COLUMN `WaterBodyID` `WaterBodyID` INT(10) NOT NULL AUTO_INCREMENT  ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
